### ISSUE TITLE
Regarding polar chart !

### ISSUE THREAD

**Issue by achinverma** [AnyChart/AnyChart-Android#1]
Hi,

i have seen your library and i want to use polar chart , i want to make a polar chart like below in screenshot , can i customize your polar chart as y0u can see in the screenshot.

1) can i set random color for each arc in the circle as now all in blue color.
2) progress of a particular section in percentage - as you can see in the image below , like if i have 40 % then my arc will be filled 40% .

Please see my requirement 
![brush- 1](https://user-images.githubusercontent.com/2811593/36143565-7b3a6ae6-10d1-11e8-96fc-fd1d04437050.png)

**Comment by Shestac92** [comment]
@achinverma 
yes, you can achieve that with AnyChart and some extra code. Please, check [code sample](https://gist.github.com/ArsenyMalkov/928776f69596da771d2781e64912d19b)  to see how it can be implemented. 
This code should render the similar chart
![custom_polar_chart](https://user-images.githubusercontent.com/24609062/36193657-b5a9a7c0-11a1-11e8-9a99-599f5e86acbe.jpg)
Hope this will help you!

**Comment by achinverma** [comment]
@Shestac92 thanks

**Comment by achinverma** [comment]
@Shestac92 ,i have used your code , one section's text is not visible, as you can see in the screenshot
createSeries(new ValueDataEntry("Restructure", 40));
Restructure text in not showing by using your above code.
![device-2018-02-26-111924](https://user-images.githubusercontent.com/2811593/36655592-9b8e3576-1ae9-11e8-87a3-eada0c9e548f.png)

**Comment by Shestac92** [comment]
@achinverma 
Sometimes this may occur when the label doesn't suit the label bounds. You can use another font size to suit it like this -  
polar.getXAxis().getLabels().setFontSize(6);
This should work!

**Comment by achinverma** [comment]
@Shestac92 ,thanks for your reply, i will try this solution.
