### ISSUE TITLE
A way to load chart in activity before it is presented?

### ISSUE THREAD

**Issue by rafayk7** [AnyChart/AnyChart-Android#103]
Hey! Just for performance reasons, is there a way to render the graphs in the activity before they are to be presented. I know there is a way to dynamically change data in graphs, so I was thinking if we can load a skeleton graph and then just dynamically change it with the data.

The use-case for me is I have a recyclerview with about 100 items, and each has its own data for 2 graphs, but the type of the graph is the same. So, if I can load a skeleton graph in the recyclerview, and then when the activity to view the graph is clicked on, the graph is loaded (faster now) and the data is changed to the specific item. Let me know if this is possible!

**Comment by Shestac92** [comment]
@rafayk7 
Yes, it's possible to render an empty chart and then add/update data. To create a skeleton graph you should create the chart as usual, but don't apply data and don't create any series.
Actually, the following code is enough to create empty Area chart:
```
        AnyChartView anyChartView = (AnyChartView) findViewById(R.id.any_chart_view);
        Cartesian chart = AnyChart.area();
        anyChartView.setChart(chart);
```

Then you can add some data, create a series. And then update data or recreate series.

**Comment by rafayk7** [comment]
Sorry, I don't think I was clear in my question! This may not be possible but would help a lot performance wise. So right now, in Activity A, I have a RecyclerView with ~100 items. Each item has a button to load Activity B with the same graphs (2 AnyChartViews). Now I'm wondering, is there a way to render the skeleton chart in Activity A (before the user has pressed any buttons) and when the user clicks on an item, it updates those charts with the data for the specific item. Is this at all possible? I may need to change the architecture of Activity B, as I'm not sure about moving Views between activities. But, let me know if you have any ideas!

**Comment by Shestac92** [comment]
@rafayk7 
Yes, unfortunately, copying or moving activities can bring unexpected behavior. As I mentioned previously, you can create a view and an empty chart before the user's actions. When the user has chosen any option the existing empty chart can be updated with new data. It will work if the chart type is the same for those options.

**Comment by rafayk7** [comment]
Thank you! :) That sounds good
