### ISSUE TITLE
bar chart doesn't update data when clicked on a button

### ISSUE THREAD

**Issue by Rashidalee** [AnyChart/AnyChart-Android#107]
it doesn't update the previous data when clicked on the button.

**Comment by Shestac92** [comment]
@Rashidalee 
The same issue was raised previously and the solution was provided in [my comments below](https://github.com/AnyChart/AnyChart-Android/issues/97#issuecomment-498983079). Please, check that thread, this should help you.

**Comment by Rashidalee** [comment]
@Shestac92  i have figured it out, thank you for your response
