### ISSUE TITLE
How can I make the temperature graph dynamic, such that it is able to update the random values given without need of closing the app

### ISSUE THREAD

**Issue by aishjain** [AnyChart/AnyChart-Android#108]
package com.anychart.sample.charts;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

import com.anychart.AnyChart;
import com.anychart.AnyChartView;
import com.anychart.chart.common.dataentry.SingleValueDataSet;
import com.anychart.charts.LinearGauge;
import com.anychart.enums.Anchor;
import com.anychart.enums.Orientation;
import com.anychart.enums.Position;
import com.anychart.sample.R;
import com.anychart.scales.Base;
import com.anychart.scales.Linear;

public class ThermometerActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_chart_common);

        AnyChartView anyChartView = findViewById(R.id.any_chart_view);
        anyChartView.setProgressBar(findViewById(R.id.progress_bar));

        LinearGauge linearGauge = AnyChart.linear();

        // used this section to generate random data 

		int random = (int)(Math.random() * 50 + 1);
        linearGauge.data(new SingleValueDataSet(new Integer[] { random }));

        linearGauge.tooltip()
                .useHtml(true)
                .format(
                        "function () {\n" +
                        "          return this.value + '&deg;' + 'C' +\n" +
                        "            ' (' + (this.value * 1.8 + 32).toFixed(1) +\n" +
                        "            '&deg;' + 'F' + ')'\n" +
                        "    }");

        linearGauge.label(0).useHtml(true);
        linearGauge.label(0)
                .text("C&deg;")
                .position(Position.LEFT_BOTTOM)
                .anchor(Anchor.LEFT_BOTTOM)
                .offsetY("20px")
                .offsetX("38%")
                .fontColor("black")
                .fontSize(17);

        linearGauge.label(1)
                .useHtml(true)
                .text("F&deg;")
                .position(Position.RIGHT_BOTTOM)
                .anchor(Anchor.RIGHT_BOTTOM)
                .offsetY("20px")
                .offsetX("47.5%")
                .fontColor("black")
                .fontSize(17);

        Base scale = linearGauge.scale()
                .minimum(-30)
                .maximum(40);
//                .setTicks

        linearGauge.axis(0).scale(scale);
        linearGauge.axis(0)
                .offset("-1%")
                .width("0.5%");

        linearGauge.axis(0).labels()
                .format("{%Value}&deg;")
                .useHtml(true);

        linearGauge.thermometer(0)
                .name("Thermometer")
                .id(1);

        linearGauge.axis(0).minorTicks(true);
        linearGauge.axis(0).labels()
                .format(
                        "function () {\n" +
                        "    return '<span style=\"color:black;\">' + this.value + '&deg;</span>'\n" +
                        "  }")
                .useHtml(true);

        linearGauge.axis(1).minorTicks(true);
        linearGauge.axis(1).labels()
                .format(
                        "function () {\n" +
                        "    return '<span style=\"color:black;\">' + this.value + '&deg;</span>'\n" +
                        "  }")
                .useHtml(true);
        linearGauge.axis(1)
                .offset("3.5%")
                .orientation(Orientation.RIGHT);

        Linear linear = Linear.instantiate();
        linear.minimum(-20)
                .maximum(100);
//                .setTicks
        linearGauge.axis(1).scale(linear);

        anyChartView.setChart(linearGauge);
    }
}

**Comment by Shestac92** [comment]
@aishjain 
Basically all you need to update the chart with new data is to make it active and apply new data. You can execute the code below at any moment you need to update the chart. This should help you!
```
APIlib.getInstance().setActiveAnyChartView(linearGauge);
random = (int)(Math.random() * 50 + 1);
linearGauge.data(new SingleValueDataSet(new Integer[] { random }));
```
