### ISSUE TITLE
Is it possible to import data from a CSV or JSON file into AnyChart Android?

### ISSUE THREAD

**Issue by liamEscher** [AnyChart/AnyChart-Android#116]
I could only see the documentation referring to JavaScript. I was hoping for an example showing how to import the data then display the data in a chart. Any help would be greatly appreciated.

**Comment by Shestac92** [comment]
@liamEscher 
The current version of AnyChart-Android library doesn't provide this built-in possibility. For the Android platform, it requires another approach. One can load the file using Android built-in tools, parse to a Java List or array and then apply to the chart data.

**Comment by liamEscher** [comment]
Thank you!

**Comment by liamEscher** [comment]
Is there an example of how to apply data that has been parsed into an ArrayList? Currently, I am trying to add my data to a PolarChart.

**Comment by Shestac92** [comment]
@liamEscher 
Yes, here is the [Gist of Polar chart](https://github.com/AnyChart/AnyChart-Android/blob/master/sample/src/main/java/com/anychart/sample/charts/PolarChartActivity.java) with the data from ArrayList.

**Comment by liamEscher** [comment]
Thank you again. I have one last question; Can I change the series labels in the Polar Chart?

**Comment by Shestac92** [comment]
@liamEscher 
Yes, you can modify series, labels, tooltips, axis labels using `format()` function. Below is the modified piece of code from the gist I provided previously. It enables and modifies the default series labels of the 1st series:
```
        Column series1 = polar.column(series1Data);
        series1.labels(true);
        series1.labels().format("$ {%value}");
```
Here is the result:
![Screenshot 2019-08-01 at 11 02 12](https://user-images.githubusercontent.com/24609062/62262680-2c953180-b44c-11e9-81fd-a05b2a466d2a.png)

**Comment by liamEscher** [comment]
thanks for all the help man, greatly appreciated!
