### ISSUE TITLE
Not able to implement onClick for line chart.

### ISSUE THREAD

**Issue by aadesh0118** [AnyChart/AnyChart-Android#12]
I am trying to set customise the tooltip and set some info on it. But for some reason it does not work.

    cartesian.setOnClickListener(new ListenersInterface.OnClickListener(new String[]{"x", "value"}) {
            @Override
            public void onClick(Event event) {

                Log.e("Route", "Graphs Clicked "+ event.getData().get("x") + " "+ event.getData().get("value"));

                Toast.makeText(RouteMapperActivity.this, event.getData().get("x") + ":" + event.getData().get("value"), Toast.LENGTH_SHORT).show();
                cartesian.getTooltip().setTitle("Date : " );
                cartesian.getTooltip().setFormat("Speed : ");
                setToolTip();

            }
        });

the log is printing but nothing happens to the tooltip.

**Comment by Shestac92** [comment]
@aadesh0118 
There's no need in listener at all in this case. All you need is to set formats. Replace your code with the following lines:
```java
cartesian.getTooltip().setTitleFormat("Date : {%x}");
cartesian.getTooltip().setFormat("Speed : {%value}");
```

**Comment by aadesh0118** [comment]
Okay got it. I have a question though if there is no listener then how can i take x and use it else where.

Basically on the title i am trying to print a value from a list at position {%x}

Something like this
    cartesian.getTooltip().setTitleFormat("Date : {%x}" + time_list.get(Integer.parseInt("{%x}")));

**Comment by Shestac92** [comment]
@aadesh0118 
In this case, it depends on what's the `time_list`. Is it a dataset for the chart or it's outside array/object/collection?

**Comment by fightaadeshfight** [comment]
its an outside list.

**Comment by Shestac92** [comment]
@aadesh0118 @fightaadeshfight 
In this case, unfortunately, the listener unable to handle this feature. We are planning to implement this opportunity next several weeks.

**Comment by fightaadeshfight** [comment]
oh.. okay. although i figured something.  i made the list part of the chart (like giving a thisr parameter "category"). This sort of solves my problem. Thanks anyway.

**Comment by aadesh0118** [comment]
oh.. okay. although i figured something. i made the list part of the chart (like giving a third parameter "category"). This sort of solves my problem. Thanks anyway.
