### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ddz95** [AnyChart/AnyChart-Android#123]
Hello,

I wanted to say that this library is really great but it suddenly stopped working with the following exception:

`java.lang.NullPointerException: Attempt to invoke virtual method 'com.anychart.AnyChartView$JsListener com.anychart.AnyChartView.getJsListener()' on a null object reference`

This exception shows up on this line:

Pie pie = AnyChart.pie();

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.anychart.AnyChartView$JsListener com.anychart.AnyChartView.getJsListener()' on a null object reference
        at com.anychart.APIlib.addJSLine(APIlib.java:27)
        at com.anychart.charts.Pie.<init>(Pie.java:34)
        at com.anychart.AnyChart.pie(AnyChart.java:130)
        at com.example.fitpoint.ProfileCreationActivity.setUpChart(ProfileCreationActivity.java:104)
```

I swear it was working like 3 days ago. Now I have no idea what could possibly cause this.

**Comment by joyceHong0524** [comment]
how did it go? I have a same error.

**Comment by gaminn** [comment]
Same problem here - is there any solution?

**Comment by cosmin-ionita** [comment]
I got the same error. Any solutions?

**Comment by ddz95** [comment]
In my case I forgot to inflate the view in the fragment and was wondering why it doesn't work:

```
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        final View rootView = inflater.inflate(R.layout.fragment_profile_creation_fragment01, container, false);

        return rootView;
```

**Comment by diaconori** [comment]
Same error here. Doesn't work. Used mulitple guides.

**Comment by r0b78** [comment]
same error. When onCreate the first time all good then the second time it crashes.

**Comment by universePr** [comment]
Same error

**Comment by nirvikBasnet** [comment]
Re-check if you have inflated the layout correctly.

**Comment by IgorKokorev** [comment]
Same here. It's just broken.
