### ISSUE TITLE
Sample (APK) link is down

### ISSUE THREAD

**Issue by bernaferrari** [AnyChart/AnyChart-Android#13]
This goes to nowhere: 
https://github.com/AnyChart/AnyChart-Android/raw/master/builds/sample.apk

**Comment by Shestac92** [comment]
@bernaferrari 
We are preparing new release of this APK, and this link will lead to the new version. 
Do you need the current version of APK?

**Comment by bernaferrari** [comment]
No, I built it myself. Just wanted you to know.
