### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by iqbalhood** [AnyChart/AnyChart-Android#14]
Hello Sir. I'm a Graphics Designer. I want provide a logo for you. Would you mind if I propose a new logo design for your application as my Open Source Contribution?

Thanks before.

**Comment by Shestac92** [comment]
@iqbalhood 
Hello,
thank you for your suggestion! We like the current logo, but if you make one we like better, we will consider using it.
