### ISSUE TITLE
Cannot show the chart

### ISSUE THREAD

**Issue by keieykd** [AnyChart/AnyChart-Android#15]
Among the five mobile phones, one of them  can't display the pie clearly. 
The content is as follows:
<img src="https://i.imgur.com/NtJpny0.png"/>

Mobile info:
<img src="https://i.imgur.com/iu2ZNrB.png"/>
<img src="https://i.imgur.com/27yZxfi.png"/>

**Comment by Shestac92** [comment]
@keieykd 
thank you for this report!
We will reproduce this issue and investigate it. I will back to you soon.

**Comment by keieykd** [comment]
@Shestac92 
Thank you very much for helping to fix the bug, and thanks for providing information.
