### ISSUE TITLE
how to using arithmetic logic multiply(*) in tooltip {%value}

### ISSUE THREAD

**Issue by zeylevruntime** [AnyChart/AnyChart-Android#151]
how to using arithmetic logic multiply(*) in tooltip {%value}?
i want to multiply {%value} before display with some integer/number. 
i try this code but not work
Line series3 = cartesian.line(series3Mapping);
series2.tooltip().format("31-60   : {%value}{*10}");

**Comment by Shestac92** [comment]
@zeylevruntime 
The `{%value}` always returns a string, it can be a part of calculation expression.
If you need to execute calculation, you should use formatted function.
Like this:
```
Cartesian chart = AnyChart.line();
Line series = chart.line(data);
series.tooltip().format("function() {" +
    "return '31-60 : ' + this.value * 10" +
"}");
```
Below is the result:
<img width="954" alt="sample" src="https://user-images.githubusercontent.com/24609062/78772268-1456b880-79c4-11ea-8b54-7541d1146996.png">

**Comment by zeylevruntime** [comment]
BIG THANKS,,,its work,,,

**Comment by zeylevruntime** [comment]
> 
> 
> @zeylevruntime
> The `{%value}` always returns a string, it can be a part of calculation expression.
> If you need to execute calculation, you should use formatted function.
> Like this:
> 
> ```
> Cartesian chart = AnyChart.line();
> Line series = chart.line(data);
> series.tooltip().format("function() {" +
>     "return '31-60 : ' + this.value * 10" +
> "}");
> ```
> 
> Below is the result:
> <img alt="sample" width="954" src="https://user-images.githubusercontent.com/24609062/78772268-1456b880-79c4-11ea-8b54-7541d1146996.png">

im sorry but how to adding {groupsSeparator:., decimalsCount:3} on this format, i try  series1.tooltip().format("function() {"+
                                    "return '31-60 : ' + this.value*100 " +
                                    "} {groupsSeparator:., decimalsCount:3}" 
but still error

**Comment by Shestac92** [comment]
@zeylevruntime 
Formatters support two approaches: string tokens and callback functions. There's no possibility to combine them. To format the number in a callback function you should use the library API. Below is the modified code:
```
series.tooltip().format("function() {" +
                "return '31-60 : ' + anychart.format.number(this.value * 10, {decimalsCount: 3, groupsSeparator:'.'})" +
                "}");
```
You can learn more about formatting toolsipts in [the guide](https://docs.anychart.com/Common_Settings/Text_Formatters).

**Comment by zeylevruntime** [comment]
thanks its work
