### ISSUE TITLE
Anychart android library not rendering chart when there is a single value or when y axis values are same

### ISSUE THREAD

**Issue by jomingeorge** [AnyChart/AnyChart-Android#154]
When i try to generate  the graph with a single value, it is just showing an empty graph (It is supposed to show a single dot in the graph indicating the value right?).

The problem also persists if the first and second y axis value is same (When there is just 2 values).

Any ideas why this weird problem occurs?

**Comment by Shestac92** [comment]
@jomingeorge 
The expected behavior depends on the chart type you are using and the exact data.
Please, can you specify the chart type and the data? Or simply share the chart configuration code.

**Comment by jomingeorge** [comment]
Hi, Thanks for the reply. The code am using is given below.

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        List<String> datelist = new ArrayList<String>();
        List<Float> weightlist = new ArrayList<Float>();
        datelist.add("12/Apr/2020");
        weightlist.add(72f);
        datelist.add("13/Apr/2020");
        weightlist.add(72f);

        LineChartView chart = findViewById(R.id.chart);

        List<AxisValue> axisValues = new ArrayList<AxisValue>();
        List<PointValue> values = new ArrayList<PointValue>();
        for (int i = 0; i < datelist.size(); ++i) {
            values.add(new PointValue(i, weightlist.get(i)));
            axisValues.add(new AxisValue(i).setLabel(datelist.get(i)));
        }

        Line line = new Line(values).setColor(Color.BLUE).setCubic(false);
        line.setHasLabels(true);
        List<Line> lines = new ArrayList<Line>();
        lines.add(line);

        LineChartData data = new LineChartData();
        data.setLines(lines);

        data.setAxisXBottom(new Axis(axisValues));
        data.setAxisYLeft(new Axis());

        chart.setLineChartData(data);


    }
}

**Comment by Shestac92** [comment]
@jomingeorge 
Are you sure that you are using AnyChart Android library?
The API you are using is not related to AnyChart library. Actually, I don't see anything from AnyChart.

**Comment by jomingeorge** [comment]
oops it's hellochart. :( Really sorry.
