### ISSUE TITLE
How to set tooltip axis color , height?

### ISSUE THREAD

**Issue by zeylevruntime** [AnyChart/AnyChart-Android#155]
![IMG_20200415_112735](https://user-images.githubusercontent.com/9654699/79298825-75bee000-7f0c-11ea-82a2-4ca279235953.jpg)
How to set tooltip axis color , height? the axis which I marked in orange arrow

**Comment by Shestac92** [comment]
@zeylevruntime 
This is a crosshair. You can adjust it's appearance using `xStroke()` and `yStroke()` functions.
Here is [the description](https://api.anychart.com/v8/anychart.core.ui.Crosshair#yStroke) of the method.
For example, you can adjust it like this:
```
        chart.crosshair(true);
        chart.crosshair().yStroke("red", 2, "0", "round", "round");
        chart.crosshair().xStroke("blue", 2, "8", "round", "round");
```
Below is the result
<img width="408" alt="sample" src="https://user-images.githubusercontent.com/24609062/79302831-0226ce00-7f20-11ea-8707-bfa3cb9c27ec.png">

**Comment by zeylevruntime** [comment]
thanks its work, 
i am sorry ask again ,how to draw gridline without click anything like this attached picture?
gridline showing in background of chart line
![Gridlines](https://user-images.githubusercontent.com/9654699/79314800-62bc0800-7f2c-11ea-8a3f-7f8f818958f2.png)

**Comment by zeylevruntime** [comment]
thanks,its work..
sorry i ask again, i use yMinorGrid,xMinorGrid to make grid line background like buble chart.
my question :
1. how to set width and color of yMinorGrid,xMinorGrid?
i am already try like figure below
![Gridlines1](https://user-images.githubusercontent.com/9654699/79405181-deb26080-7fbd-11ea-99d9-869b05c91461.png)

2. how to set width and color of chart xAxis and yAxis?

**Comment by zeylevruntime** [comment]
updated :
i try 
`cartesian.yGrid(true).selectMarqueeFill("#2D303C",10);
 cartesian.xGrid(true).selectMarqueeFill("#2D303C",10);`

`cartesian.yGrid(true).selectMarqueeStroke("#2D303C",1,"0","round","round");
 cartesian.xGrid(true).selectMarqueeStroke("#2D303C",1,"0","round","round");`
`cartesian.yGrid(true).selectMarqueeStroke("red",1,"0","round","round");
 cartesian.xGrid(true).selectMarqueeStroke("red",1,"0","round","round");`

`cartesian.xMinorGrid(true).selectMarqueeStroke("#2D303C",1,"0","round","round");
 cartesian.yMinorGrid(true).selectMarqueeStroke("#2D303C",1,"0","round","round");`

its all not success,gridline cannot change

![c2](https://user-images.githubusercontent.com/9654699/79409960-5f2a8e80-7fc9-11ea-8856-c82155afd812.PNG)

**Comment by zeylevruntime** [comment]
finally i found the answer 
![c3](https://user-images.githubusercontent.com/9654699/79411795-f265c300-7fcd-11ea-9ce9-8deace2cac56.PNG)
`   cartesian.yGrid(0).stroke("#707070",0.1,"0",null,null);
        cartesian.xGrid(0).stroke("#707070",0.1,"0",null,null);
        cartesian.xMinorGrid(0).stroke("#707070",0.1,"0",null,null);;
        cartesian.yMinorGrid(0).stroke("#707070",0.1,"0",null,null);;
`

**Comment by Shestac92** [comment]
@zeylevruntime 
You are right!
To adjust axes color you can use the same `stroke()` function.
Like this:
```
cartesian.xAxis(0).stroke("#707070",0.1,"0",null,null);
cartesian.yAxis(0).stroke("#707070",0.1,"0",null,null);
```
