### ISSUE TITLE
Is the map of India and its regions available?

### ISSUE THREAD

**Issue by sumitbisht-axestrack** [AnyChart/AnyChart-Android#16]
Like the maps of England , Australia and USA are available. Is India's map available or is there a way to add it?

**Comment by Shestac92** [comment]
@sumitbisht-axestrack 
Yes, you can download the map of India from our [CDN](https://www.anychart.com/download/cdn/).
Also, you can check the demo of using the required map [here](https://playground.anychart.com/geodata/1.2.0/countries/India).

**Comment by sumitbisht-axestrack** [comment]
ok got it !!
 but why is this map showing Jammu & kashmir region different as compared to google maps . as you can see the difference in both the pictures.

![untitled](https://user-images.githubusercontent.com/40199353/41345540-9f280054-6f21-11e8-946f-c1cb7058d526.png)
![untitled1](https://user-images.githubusercontent.com/40199353/41345542-9f57e24c-6f21-11e8-8664-1223005b326f.png)

Is there a way to Customize this India GeoJSON  as shown in google map.

**Comment by Shestac92** [comment]
Yes, it's possible. I've modified the map according to your requirements. The modified geoJSON you can find below.
[india.geojson.zip](https://github.com/AnyChart/AnyChart-Android/files/2101007/india.geojson.zip)

The demo using this custom map you can find here [here](https://playground.anychart.com/nVihk01g).

Guide about customizing maps in geoJSON you can find [here](https://docs.anychart.com/Maps/Custom_GeoJson_Maps).

**Comment by sumitbisht-axestrack** [comment]
really appreciate your help.
