### ISSUE TITLE
two chart in one activity , first chart can not render why???

### ISSUE THREAD

**Issue by zeylevruntime** [AnyChart/AnyChart-Android#167]
i have two chart in one activity and layout, but first activity cannot render.
its my layout before :
![Screenshot_2020-05-08-14-34-58](https://user-images.githubusercontent.com/9654699/81382808-28afe180-9139-11ea-9063-8191b14693b3.png)
its my layout after :
![Screenshot_2020-05-08-14-32-01](https://user-images.githubusercontent.com/9654699/81382810-29e10e80-9139-11ea-8418-fc5470558e1e.png)

why can't render 2 charts in 1 activity? I tried to reverse the line of code it turns out that only the last chart can be rendered

my code :
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:background="@drawable/bg_abu3"
    android:layout_height="match_parent"
    tools:context=".activity.HomeActivity">
    <LinearLayout
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <include layout="@layout/toolbar1"/>
        <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
            android:id="@+id/swipe"
            android:layout_width="match_parent"
            android:layout_height="match_parent">
            <LinearLayout
                android:orientation="vertical"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <LinearLayout
                android:id="@+id/lay_chart1"
                android:layout_weight="1"
                android:layout_marginBottom="10dp"
                android:layout_centerHorizontal="true"
                android:orientation="vertical"
                android:layout_width="match_parent"
                android:layout_height="match_parent">
                <TextView
                    android:layout_marginTop="10dp"
                    android:id="@+id/tv1"
                    android:textSize="20dp"
                    android:textColor="@color/white"
                    android:fontFamily="@font/quicksand_medium"
                    android:text="Aging History"
                    android:layout_gravity="center"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"/>

                <com.anychart.AnyChartView
                    android:id="@+id/chart1"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    />

                        </LinearLayout>
                <LinearLayout
                    android:id="@+id/lay_chart2"
                    android:layout_weight="1"
                    android:layout_marginBottom="10dp"
                    android:layout_centerHorizontal="true"
                    android:orientation="vertical"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">
                    <TextView
                        android:layout_marginTop="10dp"
                        android:id="@+id/tv2"
                        android:textSize="20dp"
                        android:textColor="@color/white"
                        android:fontFamily="@font/quicksand_medium"
                        android:text="MTD"
                        android:layout_gravity="center"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"/>

                    <com.anychart.AnyChartView
                        android:id="@+id/chart2"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        />

                </LinearLayout>

            </LinearLayout>

        </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>
    </LinearLayout>

</RelativeLayout>

**Comment by Shestac92** [comment]
@zeylevruntime 
Check the following guide on how to create multiple charts in a layout - https://github.com/AnyChart/AnyChart-Android/wiki/Multiple-charts-in-a-single-layout
It describes the required options.

**Comment by zeylevruntime** [comment]
its work,thanks..
