### ISSUE TITLE
how to handle click in treeMap

### ISSUE THREAD

**Issue by AxestrackKrishnji** [AnyChart/AnyChart-Android#17]
how to get the product name and the value when i am clicking on particular product in treeMap?

**Comment by Shestac92** [comment]
@AxestrackKrishnji 
Here is a [Gist](https://gist.github.com/ArsenyMalkov/515f8ddabd5c3e0910c6a151a1fba711) which describes how to create such listener.

**Comment by AxestrackKrishnji** [comment]
I have created listener as you have told but its is not giving the correct product and value, it gives random  product and its value. can you please tell me how to resolve this problem ?

**Comment by Shestac92** [comment]
@AxestrackKrishnji 
Thank you for your report! We've just checked it and we confirm this bug. It happens when you click the point label. If you click somewhere around the label it returns the correct value. I will report it to our dev team. Also, I will notify you when I get new information, ETA on fix or solution.

**Comment by Shestac92** [comment]
@AxestrackKrishnji 
we will do our best to provide the fix along with the release of 8.3.0 or 8.3.1 version within next three weeks.
We will notify you when the fix becomes available.

**Comment by AxestrackKrishnji** [comment]
Hello Alexander,

can you please tell me when you are going to release your next version with
resolve treemap issues ?

Thanks & Regards
Krishnji Gupta

**Comment by Shestac92** [comment]
@AxestrackKrishnji 
Please, try to update the AnyChart Android library. The latest version should work properly with treeMap interactivity. Please, let us know if you still face the problem.

**Comment by AxestrackKrishnji** [comment]
After updating the library, it is showing error like below :

Error:(150, 20) Failed to resolve:
com.github.AnyChart:AnyChart-Android:0.3.0
<a
href="openFile:/home/akshay/Pictures/TrackOld/track-your-monitor-feelt-new/app/build.gradle">Show
in File</a><br><a href="open.dependency.in.project.structure">Show in
Project Structure dialog</a>


@Alexander
Can you please tell me how to resolve this issue ?

**Comment by ArsenyMalkov** [comment]
@AxestrackKrishnji 
Please check that jitpack was added to the **project build.gradle** at the end of repositories.
```Gradle
allprojects {
        repositories {
                google()
                jcenter()
                maven { url 'https://jitpack.io' }
        }
}
```

Also you could try again a little bit later. Some people say that dependency become available after few hours.

**Comment by ArsenyMalkov** [comment]
@AxestrackKrishnji 
We found out the problem and fixed it. Please try to build a project again. And please let us know if you have any problems.
