### ISSUE TITLE
Is zoom and move in Line Chart possible ?

### ISSUE THREAD

**Issue by hannesa2** [AnyChart/AnyChart-Android#173]
I tried to use a LineChart and I know there is a 

```
anyChartView.setZoomEnabled(true);
AnyChart.line();
```
but is there anyhow the ability to move zoomed area in x-axis as well out of the box ?

**Comment by Shestac92** [comment]
@hannesa2 
The Line chart support xScorller that can be enabled like this:
```
chart.xScroller(true);
```

**Comment by hannesa2** [comment]
I see you scroll the complete screen, included axis, and not only data area
