### ISSUE TITLE
Map loading is very slow for Choropleth Map.

### ISSUE THREAD

**Issue by aadesh0118** [AnyChart/AnyChart-Android#18]
I am drawing India's map in here. But the map drawing is really slow. The data is a lot (like 1200 models).
But after the models are added the map takes about 5 minutes to display on the screen.

What could be the reason?
Is there a way to make it faster?

**Comment by Shestac92** [comment]
@aadesh0118 
We'd like to clarify a few moments here. Do you use India's map provided by AnyChart or third-party map?
1200 models - do you mean 1200 points on the map with related values, right?
