### ISSUE TITLE
How to add icon to each cell in treeMap

### ISSUE THREAD

**Issue by ahmedKhaledMohammed** [AnyChart/AnyChart-Android#182]
I want to add icon for each item as attached , and add multi values as several labels

**Comment by Shestac92** [comment]
@ahmedKhaledMohammed 
Unfortunately, the current version of the library doesn't support image icons in the Treemap chart.
You can show multiple values in multiline labels like it is shown [in the Gist](https://gist.github.com/Shestac92/63374d6e163019ea3843dd8c8493c198).

Below is the resulting chart.
<img width="416" alt="Screenshot 2020-06-29 at 11 27 43" src="https://user-images.githubusercontent.com/24609062/85970074-e51c7a00-b9fb-11ea-9dc0-67f5e327b249.png">
