### ISSUE TITLE
Create X amount of series dynamically

### ISSUE THREAD

**Issue by Fdde11** [AnyChart/AnyChart-Android#183]
I was using a CustomDataEntry to show 4 series in a char, something like this:
```Java
    private class CustomDataEntry extends ValueDataEntry {
        CustomDataEntry(String x, Number value, Number value2, Number value3, Number value4) {
            super(x, value);
            setValue("value2", value2);
            setValue("value3", value3);
            setValue("value4", value4);
        }
    }
```
but I now require to show a not fixed amount of series, so my char could have 2 or 5 or 'N' amount of series, how can I do this?

**Comment by Shestac92** [comment]
@Fdde11 
You can create multiple Lists of ValueDataEntry dynamically and apply them to the chart series.
It means that you can create one list and map it to multiple series or you can create multiple lists of simple ValueDataEntry.

**Comment by Fdde11** [comment]
This is what I did, it worked for me.

```Java
private class CustomDataEntry extends ValueDataEntry {
    CustomDataEntry(String x, Number[] value) {
        super(x, value[0]);
        for(int y=1;y<value.length;y++)
        {
          setValue("value"+(y+1), value[y]);
        }
    }
}
```
