### ISSUE TITLE
AnyChart Android PlotController.Ellipse.allowEdit expects a string instead of a boolean

### ISSUE THREAD

**Issue by Markieautarkie** [AnyChart/AnyChart-Android#189]
Hello,

I am a bit confused about the allowEdit function of the Ellipse class. I want disable the ability to edit the ellipse, but I am unsure what kind of value I have to pass in the string for that.

Code snippet of the problem:
![image](https://user-images.githubusercontent.com/11558887/90924713-40615c00-e3f0-11ea-88cf-f7499a596feb.png)

Thanks in advance!

(Little side question, but I can't seem to access the ticks() function for the x/y grid respectively either. What would be the appropriate way to set tick intervals on Android?)

**Comment by Shestac92** [comment]
@Markieautarkie 
Thank you for pointing us to the issue.
This is a mistake, the `allowEdit()` function should have a boolean argument instead of String. Unfortunately, there's no workaround for that in the current version. We will take into account for a future update.

**Comment by Markieautarkie** [comment]
@Shestac92 
Thanks for the swift response.
Would there be a way to approach such an annotation with the Ellipse/Circle classes of the vector-graphics related class? I tried instantiating them directly and via staging, yet I didn't have success with either of them.

**Comment by Shestac92** [comment]
@Markieautarkie 
I'm not sure that it will be available in the nearest releases. But we will take it into account.
