### ISSUE TITLE
Transparent background of graph

### ISSUE THREAD

**Issue by BeefxWellington** [AnyChart/AnyChart-Android#194]
Reading the documentation and API reference I see that with chart.background(), and the variations of it, can color the background including transparent with the hex as well. However the transparent hex only leaves the background white. 

Does your API offer an option to make it truly transparent to the color of the xml code that the graph sits on top of? Alternatively would it be possible to set the background to a drawable from resources like in xml?

Reference screenshot: https://drive.google.com/file/d/1A1XQzqDngWjWbBR_E4iRPDhsIcn53ceW/view?usp=sharing

**Comment by Shestac92** [comment]
@BeefxWellington 
Unfortunately, the current version of the library doesn't support that. We will take it into account for future updates.

**Comment by BeefxWellington** [comment]
@Shestac92 Thank you for the quick response and consideration.
