### ISSUE TITLE
Using Palette in Column Chart

### ISSUE THREAD

**Issue by A-Nikhil** [AnyChart/AnyChart-Android#197]
I got a color assigned to different entities in a column chart. I am including only those entities in the chart data which are required and creating a palette of the same.

Here's an example code
```java
        List<DataEntry> dataForColumn1 = new ArrayList<>();
        dataForColumn1.add(new ValueDataEntry("Food", 30));
        dataForColumn1.add(new ValueDataEntry("Work", 40));
        dataForColumn1.add(new ValueDataEntry("Education", 50));
        
        String[] palette1 = new String[]{"#F4D03F", "#5DADE2", "#D98880"};

        columns.data(dataForColumn1);
        columns.palette(palette1);
```

![image](https://user-images.githubusercontent.com/38154602/96477493-31622300-1254-11eb-8206-9d5d31907213.png)

Shouldn't I be getting different colored columns?

**Comment by Shestac92** [comment]
@A-Nikhil 
No, the palette colors are assigned to different series, not bars. It means that the 1st series will be colored with "#F4D03F", the 2nd series with "#5DADE2", etc.
To color bars individually you should [the approach described in the gist](https://gist.github.com/Shestac92/762b768c0e0a8ac17dd42485d76105a4).

**Comment by A-Nikhil** [comment]
@Shestac92 
Thanks again for the help!!
