### ISSUE TITLE
Axis Scroller for Scatter Chart

### ISSUE THREAD

**Issue by A-Nikhil** [AnyChart/AnyChart-Android#198]
Hi
Are there any Axis Scrollers for Scatter Chart? I am having to display about 31 entries on the xAxis on a portrait display and I want to know if there any scrollers for that? Like there are `xScroller()` in the Line Charts.

Also, is there any way I can make my chart Swipe-enabled? Displaying 10 entries in one go, then as we swipe, the other entries come while the Y-axis remains fixed?

**Comment by Shestac92** [comment]
@A-Nikhil 
The scatter chart supports scrollers just like it is shown [in the article](https://docs.anychart.com/Common_Settings/Scroller).

**Comment by A-Nikhil** [comment]
@Shestac92 
I could not find anything that is working with the Scatter Chart. My chart variable is `Scatter scatter = AnyChart.scatter()`

**Comment by Shestac92** [comment]
@A-Nikhil 
Unfortunately, the Scatter chart doesn't support the scroller in the Android native library.
