### ISSUE TITLE
merger conflict

### ISSUE THREAD

**Issue by Vivektilva** [AnyChart/AnyChart-Android#2]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@name value=(com.crm.volley.AppController) from AndroidManifest.xml:22:9-45
  	is also present at [com.github.AnyChart:AnyChart-Android:0.1.0] AndroidManifest.xml:12:9-71 value=(com.anychart.anychart.application.MyApplication).
  	Suggestion: add 'tools:replace="android:name"' to <application> element at AndroidManifest.xml:21:5-322:19 to override.

I tried to add tools:replace but it is not working ...

Can u suggest any solution? @Shestac92 @ArsenyMalkov

**Comment by Shestac92** [comment]
@Vivektilva 
thank you for the report! We investigated this issue and made hotfix. Please, try 0.1.1 version, it should work perfectly. And please, let us know if there are any problems.

**Comment by Vivektilva** [comment]
Thank you so much for instant reply and fix this. @Shestac92
