### ISSUE TITLE
Vertical Chart misses few labels.

### ISSUE THREAD

**Issue by aadesh0118** [AnyChart/AnyChart-Android#20]
Hi , 
I am using vertical chart from your library. When data is about 20 a few labels are missed on Y-axis. 
Is there a way to resolve this issue?
Thanks.
![screenshot_20180703_141900](https://user-images.githubusercontent.com/36659303/42210718-58c8137a-7ecf-11e8-9400-d621b0d2e9a4.png)

**Comment by aadesh0118** [comment]
Thanks, that solves it. But i encountered something similar in Choropleth Map. I added Indian map in my app. 
Some states didnot have numbers in them when data was more. Is it because of the same reason? To avoid overlapping or that is something different?

**Comment by aadesh0118** [comment]
Like if we look at the example that you have given of the USA map.
 The states of Illinois and Indiana have no labels on them but you have given data in your code.

I am facing the same issue.

**Comment by Shestac92** [comment]
@aadesh0118 
Yes, for maps logic is absolutely the same. But you can force the map to show all labels despite of overlapping. You can achieve this like this:
```
map.setOverlapMode(LabelsOverlapMode.ALLOW_OVERLAP);
```
The same approach is used in [this sample of USA states map](https://playground.anychart.com/bCr5UrUv).

**Comment by aadesh0118** [comment]
Thanks for your help. Appreciate it.
