### ISSUE TITLE
Start with initial value

### ISSUE THREAD

**Issue by anujkalal** [AnyChart/AnyChart-Android#21]
![device-2018-07-03-175712](https://user-images.githubusercontent.com/12730923/42219761-9ccf81dc-7eea-11e8-9a86-3110b4e9a252.png)
Start the x axis and y axis origin from 65 and 5.

**Comment by Shestac92** [comment]
@anujkalal 
Now you are using default ordinal scale, which always places gaps on sides. In this case, you should use linear x-scale and set manually scale minimum for x- and y-scale. You can achieve that like this:
```
ScalesLinear linear = new ScalesLinear();
linear.setMinimum(65);
chart.setXScale(linear);
chart.getYScale().setMinimum(5);
```

**Comment by tomgallagher** [comment]
How can you set the equivalent to Javascript `chart.xScale().mode('continuous');`?
