### ISSUE TITLE
disabling touch in Sparkline chart in android

### ISSUE THREAD

**Issue by iamomidk** [AnyChart/AnyChart-Android#211]
how to disable the touch input in Sparkline chart in android

**Comment by Shestac92** [comment]
@iamomidk 
Can you specify what exactly actions do you want to prohibit? Showing the tooltip?

**Comment by iamomidk** [comment]
yes exactly.

**Comment by Shestac92** [comment]
You can simply disable the tooltip like this:
```
        Sparkline chart = AnyChart.sparkline();
        chart.tooltip(false);
```
