### ISSUE TITLE
Mistake in map world

### ISSUE THREAD

**Issue by CharlotteJu** [AnyChart/AnyChart-Android#218]
Hi ! 

I've a problem with the map's script (World Source) : https://cdn.anychart.com/releases/8.9.0/geodata/custom/world_source/world_source.js
!

Some country are not at the good place visibly ... 

Like, in this example, Russia (in gray) or France (in purple). I don't understand, because in this [link](https://playground.anychart.com/geodata/2.1.0/custom/World), that looks great ! 

![Screenshot_20210409-145654_Gif Itch](https://user-images.githubusercontent.com/54888583/114183851-68340e80-9944-11eb-92bf-ff9eb3382ad0.jpg)

In my code, I just do : 

` val url = "https://cdn.anychart.com/releases/8.9.0/geodata/custom/world_source/world_source.js"
        mView.anyChartViewCountry.addScript(url)`

Can you tell me if the error is only on my side ? 

Thanks !

**Comment by Shestac92** [comment]
@CharlotteJu 
Make sure that you have added the library for geo calculations:

`anyChartView.addScript("file:///android_asset/proj4.js");`

The library is available by [the link](https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.15/proj4.js).

**Comment by CharlotteJu** [comment]
> @CharlotteJu
> Make sure that you have added the library for geo calculations:
> 
> `anyChartView.addScript("file:///android_asset/proj4.js");`
> 
> The library is available by [the link](https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.15/proj4.js).

Hi @Shestac92 
I've add it, but nothing has changed ... 

`val urlWorld = "https://cdn.anychart.com/releases/8.9.0/geodata/custom/world_source/world_source.js"`
`val urlProJS = "https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.15/proj4.js"  `  
`mView.anyChartViewCountry.addScript(urlWorld)`
`mView.anyChartViewCountry.addScript(urlProJS)`

**Comment by CharlotteJu** [comment]
I think I understood the problem, but I don't know how to fix it ...

In my exemple, France and Russia have many territories in the world, and the bubble get in the middle.

(France light blue, Russia dark blue)

<img width="401" alt="image" src="https://user-images.githubusercontent.com/54888583/114395879-2e117980-9b9d-11eb-9700-562658ba300b.png">

Does anyone know how to put the bubble in a specific location?

**Comment by Shestac92** [comment]
@CharlotteJu 
Got it!
I thought you were using geo-coordinates for markers...
Yes, some countries have separated territories. If you are using country ID for placing markers, then the markers is placed in the geometry center of the whole country territory.

In this case, we recommend using geo-coordinates for markers. For details, check [the snippet](https://github.com/AnyChart/AnyChart-Android/blob/master/sample/src/main/java/com/anychart/sample/charts/PointMapActivity.java).

**Comment by CharlotteJu** [comment]
Thanks a lot, it's good !!
