### ISSUE TITLE
Chart is not showing up

### ISSUE THREAD

**Issue by Sorwar-Hosen-Mostafa** [AnyChart/AnyChart-Android#22]
i have implemented the chart view in my app acording to the procedure which is given in the doc, but chart is not showing up, A little text calling anychart trial version is showing at the below.

here is my code,

Gradle:

    `apply plugin: 'com.android.application'

    android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.gdm.chartsapp"
        minSdkVersion 20
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    }

    dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    testImplementation 'junit:junit:4.12'

    implementation 'com.github.AnyChart:AnyChart-Android:0.2.7'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    }`

MainActivity.xml:

    `<?xml version="1.0" encoding="utf-8"?>
    <android.support.constraint.ConstraintLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.anychart.anychart.AnyChartView
        android:background="@color/black"
        android:id="@+id/any_chart_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        />

    </android.support.constraint.ConstraintLayout>`

MainActivity.java:

    import android.support.v7.app.AppCompatActivity;
    import android.os.Bundle;

    import com.anychart.anychart.AnyChart;
    import com.anychart.anychart.AnyChartView;
    import com.anychart.anychart.DataEntry;
    import com.anychart.anychart.Pie;
    import com.anychart.anychart.ValueDataEntry;

    import java.util.ArrayList;
    import java.util.List;

    public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Pie pie = AnyChart.pie();

        List<DataEntry> data = new ArrayList<>();
        data.add(new ValueDataEntry("John", 10000));
        data.add(new ValueDataEntry("Jake", 12000));
        data.add(new ValueDataEntry("Peter", 18000));

        AnyChartView anyChartView = findViewById(R.id.any_chart_view);
        anyChartView.setChart(pie);
    }
    }`

output: 

![screenshot_20180707-103838_chartsapp](https://user-images.githubusercontent.com/29955691/42406864-36499354-81d2-11e8-8879-d34dd1a8e511.jpg)

**Comment by Shestac92** [comment]
@Sorwar-Hosen-Mostafa 
You have missed applying data to the chart. 
Below is a corrected fragment of your code:
```

List<DataEntry> data = new ArrayList<>();
data.add(new ValueDataEntry("John", 10000));
data.add(new ValueDataEntry("Jake", 12000));
data.add(new ValueDataEntry("Peter", 18000));

pie.setData(data);    // Add this line

AnyChartView anyChartView = findViewById(R.id.any_chart_view);
anyChartView.setChart(pie);
```

**Comment by Sorwar-Hosen-Mostafa** [comment]
thank you so much. its working now.
