### ISSUE TITLE
how to get values and sum that in bar chart

### ISSUE THREAD

**Issue by zeylevruntime** [AnyChart/AnyChart-Android#224]
![stc](https://user-images.githubusercontent.com/9654699/126587789-0fdc4b26-27b4-4ad8-835a-a63e6967055e.PNG)
 i want to sum data value in b1+b2+b3=result and write result in b3.labels(). How to ??
here is my code 
![d1](https://user-images.githubusercontent.com/9654699/126588077-db89ba30-b8c8-4f93-9dc4-d9b00e8c9e4f.PNG)
![d2](https://user-images.githubusercontent.com/9654699/126588079-e8ed7f6f-b1fb-44d7-ad54-de5782bf1097.PNG)

**Comment by Shestac92** [comment]
@zeylevruntime 
You can achieve that using a special string token for the b3 labels. Try the line below:
```
b3.labels().enabled(true).format("{%categoryYSum}");
```

**Comment by zeylevruntime** [comment]
how about if just b1+b2??

**Comment by Shestac92** [comment]
Unfortunately, string tokens don't provide this possibility.
