### ISSUE TITLE
Error Synching Gradle

### ISSUE THREAD

**Issue by kuyajohn** [AnyChart/AnyChart-Android#23]
Failed to resolve: com.github.AnyChart:AnyChart-Android:0.3.0

Below is my Module:app build.gradle file

```gradle
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.anychart.charts"
        minSdkVersion 17
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.github.AnyChart:AnyChart-Android:0.3.0'
}
```

**Comment by ArsenyMalkov** [comment]
@kuyajohn 
You should check that **jitpack** was added to the **project build.gradle** at the end of repositories.

Go to you **project build.gradle** and add this line if it doesn't exist:
```gradle
allprojects {
        repositories {
                google()
                jcenter()
                maven { url 'https://jitpack.io' }
        }
}
```

Also make sure you add this under allprojects not under buildscript.

**Comment by EzeroVivanco** [comment]
I'm having the same error.
I've already updated both files.

**Comment by EzeroVivanco** [comment]
I found the problem.
The dependency in the README.md has a wrong version: 
implementation 'com.github.AnyChart:AnyChart-Android:0.3.0'

The correct version should be:
implementation 'com.github.AnyChart:AnyChart-Android:3.0.0'

**Comment by ArsenyMalkov** [comment]
@EzeroVivanco 
Thank you for your report! We will fix it immediately.

**Comment by ArsenyMalkov** [comment]
@EzeroVivanco 
We have fixed this problem. Version 0.3.0 is correct one, please use it.
