### ISSUE TITLE
Run issue

### ISSUE THREAD

**Issue by Bollardinho** [AnyChart/AnyChart-Android#235]
Hello,
Im having problem with running my app after implementation of your library, this is my console output

>Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [com.github.AnyChart:AnyChart-Android:1.1.2] C:\Users\andrea\.gradle\caches\transforms-3\57d6ea40fce51fa285539c6e8036eddd\transformed\jetified-AnyChart-Android-1.1.2\AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 19,
  		or use tools:overrideLibrary="com.anychart" to force usage (may lead to runtime failures)

What should I do? Im new in android studio, so sorry for this basic questions. 

Best Regards

**Comment by Shestac92** [comment]
@Bollardinho 
AnyChart library for Android compatible with API 19+. You are using the 16 version.
