### ISSUE TITLE
funnel labels not showing when legend character are long

### ISSUE THREAD

**Issue by KallepalliTirumalesh** [AnyChart/AnyChart-Android#236]
Hi, Thank You for the library

I am facing an issue when the legend string is long the labels inside the funnel are not showing up can you please share me what need to be done to avoid this issue how can i add ellipse to the legend string.

PFA

![Sample](https://user-images.githubusercontent.com/48198600/139687880-855c3581-147f-4c7a-ba5c-5047603a2b0d.jpg)

**Comment by Shestac92** [comment]
@KallepalliTirumalesh 
You can limit the legend width in percents or pixels. Like in [the live sample](https://playground.anychart.com/m1z4ZIUv).
Unfortunately, the ellipse is not supported in the legend items.

**Comment by KallepalliTirumalesh** [comment]
Thank You
