### ISSUE TITLE
stacked funnel plots 

### ISSUE THREAD

**Issue by KallepalliTirumalesh** [AnyChart/AnyChart-Android#238]
Hi, Thank you for the library can we customise like the stacked funnel.
![funnel-chart-example](https://user-images.githubusercontent.com/48198600/142193779-ced8fa71-1688-4c00-89d3-a57fc964c269.png)

**Comment by Shestac92** [comment]
@KallepalliTirumalesh 
Unfortunately, the library doesn't provide this possibility at the moment.

**Comment by KallepalliTirumalesh** [comment]
Thank You
