### ISSUE TITLE
Could you tell me how to show Multiple charts in a Activity

### ISSUE THREAD

**Issue by jjeong0225** [AnyChart/AnyChart-Android#24]
I tried to show three charts in one Activity but just only one chart show when I run my app. 
How can I solve this problem??

**Comment by ArsenyMalkov** [comment]
We have just updated the library. Please, download the latest version and try it.

**Comment by jjeong0225** [comment]
Thank you for your Quick Response!!!!

**Comment by MartinLuna123** [comment]
I'm still having the same problem. Is it there any other realeased version? Thanks!

**Comment by MartinLuna123** [comment]
Nevermind, I was compiling 0.3.0. For the record, update the description in the main page, it says '0.3.0'
