### ISSUE TITLE
Pie chart width changing if the label is outside

### ISSUE THREAD

**Issue by rezyfr** [AnyChart/AnyChart-Android#243]
Hi, im implementing Pie chart with outside with the following code
![image](https://user-images.githubusercontent.com/22698234/151309894-3914aa4c-d039-46fe-85b7-acf3eecf4aee.png)
![image](https://user-images.githubusercontent.com/22698234/151310176-8a38bae4-6b8e-4ff9-8f7b-e208db538a3d.png)
![image](https://user-images.githubusercontent.com/22698234/151310360-e1a857c5-866c-4794-9401-56a9d7351c9d.png)
![image](https://user-images.githubusercontent.com/22698234/151310399-c961f082-12f8-4203-a9e2-394170760fb8.png)

However it shows different sizes if the data is different, I wonder what cause this and how to fix it?

And why I can't use wrap_content on the chart height? if I use wrap_content, the chart wont show anything I'm using version 1.1.2

**Comment by Shestac92** [comment]
The chart size depends on the length of the outside labels.

Unfortunately, the AnyChartView is not compatible with the wrap_content.

**Comment by rezyfr** [comment]
is there any possibility that I cant set the label size or the connector length dynamically. So the chart size will be static/fixed?

**Comment by Shestac92** [comment]
No, it's not possible in the current version of the library.

**Comment by rezyfr** [comment]
okay thankyou
