### ISSUE TITLE
Is there any way to remove the Y axis line but not the label?

### ISSUE THREAD

**Issue by rezyfr** [AnyChart/AnyChart-Android#245]
I wanna make a chart somehing like this (this is a mockup)
![image](https://user-images.githubusercontent.com/22698234/153674127-a07148f9-dbb8-4597-9ab2-e6520f743e98.png)

is there anyway to remove the line to achieve something like that? thanks

**Comment by Shestac92** [comment]
@rezyfr 
Try the code below
```
chart.yAxis(0).stroke('none');
```
