### ISSUE TITLE
the problem in treemap

### ISSUE THREAD

**Issue by jianning0925** [AnyChart/AnyChart-Android#246]
Hi, In the treemap ,How to make the size of his area different from the color value .
 such as ：
 data.add(new TreeMapChartActivity.CustomTreeDataEntry("Apples", "Fruits", "Apples", 50))；
 treeMap.colorScale().ranges(new String[]{
                "{ less: 2 }",
                "{ from: 2, to: 5 }",
                "{ from: 5, to: 20 }",
                "{ from: 20, to: 50 }",
                "{ from: 50, to: 80 }",
                "{ greater: 80 }"
        }); 

but the color need to  by other value.  

For example, the country's population is size and the birth rate is color

**Comment by jianning0925** [comment]
I see .  the treeData value control the size, and the color range , if i add a new field , how to let the color use the new field?

**Comment by Shestac92** [comment]
@jianning0925 
The color depends on the "value" field only. The size depends on "size" if it persists or on "value".
So, you need both in this case.

**Comment by jianning0925** [comment]
ok ,Thank you for the answer
