### ISSUE TITLE
Download it and run it, click on the page and nothing is displayed

### ISSUE THREAD

**Issue by BaiMingxu** [AnyChart/AnyChart-Android#254]
Blank page, why

**Comment by CatLoli** [comment]
me too !!!

**Comment by zpf527** [comment]
me too

**Comment by zpf527** [comment]
fix
//    implementation project(":anychart")
    implementation 'com.github.AnyChart:AnyChart-Android:1.1.2'

**Comment by kojofosu** [comment]
> fix // implementation project(":anychart") implementation 'com.github.AnyChart:AnyChart-Android:1.1.2'

This fixes for pie charts only....it doesn't fix bar charts..sad :(

**Comment by kiann** [comment]
me too ，with xiaomi 2 and huawei nova3 ,all type charts is full white screen , only show 'anyChart trial version' on the bottom right ,so sad

**Comment by black-pwq** [comment]
use version 1.1.2 instead of 1.1.4 and add android.enableJetifier=true to gradle.properties.
