### ISSUE TITLE
remove "AnyChart Trial Version" text

### ISSUE THREAD

**Issue by majdalden** [AnyChart/AnyChart-Android#26]
hello

How do I delete text at the bottom of the graph "AnyChart Trial Version"?

https://i.imgur.com/kMJUu0p.png

and How do I  change the colour of ValueDataEntry???

**Comment by Shestac92** [comment]
@majdalden 
Please, check [this article](https://github.com/AnyChart/AnyChart-Android/wiki/Credits) which describes how to adjust or disable credits ("AnyChart Trial Version" sign).

You can define your own set of colors for pie sectors like this:
```
pie.setPalette(new String[]{ "#fff", "#fff", "#fff", "#fff", "#fff" });
```

**Comment by majdalden** [comment]
@Shestac92 

Thank you

The colour has changed but the text "AnyChart Trial Version"  has not been disabled

Is there a better way?

**Comment by Shestac92** [comment]
@majdalden 
To disable credits just put this in your code, but remember: it will work only if you have a license key.
`chart.getCredits().setEnabled(false);`

To purchase a license key, please, visit [the buy page](https://www.anychart.com/buy/) on [official AnyChart site](https://www.anychart.com/).

**Comment by AbanoubWagdyy** [comment]
chart.getCredits().setEnabled(false); can not be resolved 
any idea ?!

**Comment by Wawhaha** [comment]
Replace your script anychart-base.min.js with the attached file. Hope it can help | it works on my side.
