### ISSUE TITLE
When I add chart, cant see anything in designer

### ISSUE THREAD

**Issue by Midza43** [AnyChart/AnyChart-Android#260]
When I add a chart to my design, I cant see my design anymore. Help
![image](https://user-images.githubusercontent.com/117947826/201206229-9185da28-8235-4c2d-a39e-8963d833f040.png)
![image](https://user-images.githubusercontent.com/117947826/201206254-3426d542-0eb1-4cab-9b1d-33e54f8f6d72.png)

**Comment by aeharake** [comment]
What happend to this issue?

**Comment by Midza43** [comment]
Solved!

**Comment by aeharake** [comment]
> Solved!

I was still facing the same issue on the latest version. 1.1.4
