### ISSUE TITLE
Bar chart not showing when use more then one view....

### ISSUE THREAD

**Issue by arbazejaz** [AnyChart/AnyChart-Android#262]
bar chart showing empty view when i use more then one anyChartView in fragment is there any solution for this?

**Comment by MohammedAbidNafi** [comment]
Can you show the code?

**Comment by MohammedAbidNafi** [comment]
So unfortunately this library dosent support fragments for now

**Comment by arbazejaz** [comment]
Okay thanks for response I use two different libraries for my work.
