### ISSUE TITLE
Multiple chartviews in a Single Activity

### ISSUE THREAD

**Issue by ihsanulhaq-saal-ai** [AnyChart/AnyChart-Android#31]
Can you add multiple charts in an activity? Currently, only one shows up.

**Comment by Shestac92** [comment]
@ihsanulhaq-saal-ai 
Please, can you specify which version of the AnyChart-Android library you are using?

**Comment by Shestac92** [comment]
@ihsanulhaq-saal-ai 
Please, update your version up to the latest - 1.0.1.
With the new version you can show multiple chart in a view like this:
```java
AnyChartView anyChartView = findViewById(R.id.any_chart_view);
APIlib.getInstance().setActiveAnyChartView(anyChartView);

Pie pie = AnyChart.pie();

List<DataEntry> data = new ArrayList<>();
data.add(new ValueDataEntry("Apples", 6371664));
data.add(new ValueDataEntry("Pears", 789622));
data.add(new ValueDataEntry("Bananas", 7216301));
data.add(new ValueDataEntry("Grapes", 1486621));
data.add(new ValueDataEntry("Oranges", 1200000));

pie.data(data);

pie.title("Fruits imported in 2015 (in kg)");

anyChartView.setChart(pie);

// Second chart

AnyChartView anyChartView1 = findViewById(R.id.any_chart_view1);
APIlib.getInstance().setActiveAnyChartView(anyChartView1);

Pie pie1 = AnyChart.pie();

List<DataEntry> data1 = new ArrayList<>();
data1.add(new ValueDataEntry("Apples", 6371664));
data1.add(new ValueDataEntry("Pears", 789622));
data1.add(new ValueDataEntry("Bananas", 7216301));
data1.add(new ValueDataEntry("Grapes", 1486621));
data1.add(new ValueDataEntry("Oranges", 1200000));

pie1.data(data1);

pie1.title("Fruits imported in 2015 (in kg)");

anyChartView1.setChart(pie1);
```

**Comment by ihsanulhaq-saal-ai** [comment]
Amazing!! thank you @Shestac92 so much!!

**Comment by rusiiyojr** [comment]
Hi, I can't add multiple AnyChartView on my activity. I'm using version 1.1.2. Even adding APIlib.getInstance().setActiveAnyChartView(anyChartView); after every AnyChartView declaration only one view is seen. 
Thanks.

**Comment by rusiiyojr** [comment]
> Amazing!! thank you @Shestac92 so much!!



> @ihsanulhaq-saal-ai
> Please, update your version up to the latest - 1.0.1.
> With the new version you can show multiple chart in a view like this:
> 
> ```java
> AnyChartView anyChartView = findViewById(R.id.any_chart_view);
> APIlib.getInstance().setActiveAnyChartView(anyChartView);
> 
> Pie pie = AnyChart.pie();
> 
> List<DataEntry> data = new ArrayList<>();
> data.add(new ValueDataEntry("Apples", 6371664));
> data.add(new ValueDataEntry("Pears", 789622));
> data.add(new ValueDataEntry("Bananas", 7216301));
> data.add(new ValueDataEntry("Grapes", 1486621));
> data.add(new ValueDataEntry("Oranges", 1200000));
> 
> pie.data(data);
> 
> pie.title("Fruits imported in 2015 (in kg)");
> 
> anyChartView.setChart(pie);
> 
> // Second chart
> 
> AnyChartView anyChartView1 = findViewById(R.id.any_chart_view1);
> APIlib.getInstance().setActiveAnyChartView(anyChartView1);
> 
> Pie pie1 = AnyChart.pie();
> 
> List<DataEntry> data1 = new ArrayList<>();
> data1.add(new ValueDataEntry("Apples", 6371664));
> data1.add(new ValueDataEntry("Pears", 789622));
> data1.add(new ValueDataEntry("Bananas", 7216301));
> data1.add(new ValueDataEntry("Grapes", 1486621));
> data1.add(new ValueDataEntry("Oranges", 1200000));
> 
> pie1.data(data1);
> 
> pie1.title("Fruits imported in 2015 (in kg)");
> 
> anyChartView1.setChart(pie1);
> ```

Hi, I can't add multiple AnyChartView on my activity. I'm using version 1.1.2. Even adding APIlib.getInstance().setActiveAnyChartView(anyChartView); after every AnyChartView declaration only one view is seen.
Thanks.

**Comment by Sicness** [comment]
If I add the second com.anychart.AnyChartView with a different ID, the first one becomes an empty white view. 1.1.2
