### ISSUE TITLE
Multi-Level Categories

### ISSUE THREAD

**Issue by rafvasq** [AnyChart/AnyChart-Android#33]
Is it possible to implement multi-level categories for a column chart? I noticed [this blog post](https://www.anychart.com/blog/2017/11/29/multi-level-category-axis-challenge-anychart/) which gives an example in JS, but I haven't been able to find anything for Android/Java.

Specifically, I'd like to group data by week (subcategory) per month (category).

Thanks!

**Comment by Shestac92** [comment]
@rafvasq 
Yes, this is possible with the latest update. Please, update your library, the latest version is 1.0.2 and try [this code](https://gist.github.com/ArsenyMalkov/9699bb46d1d6e999366196b6d6b11a31) to implement the required chart.
