### ISSUE TITLE
All the README documentation links link to some APK, not documentation

### ISSUE THREAD

**Issue by zlotny** [AnyChart/AnyChart-Android#39]
All the Documentation links below the chart example screenshot link to this:

`<a href="https://static.anychart.com/cdn/integrations/android-basic-sample.apk">Documentation</a>`

I believe that is not the intended purpose of the link.

**Comment by Shestac92** [comment]
@zlotny 
Thank you for pointing us to this issue! We have just removed the deprecated link.
