### ISSUE TITLE
Cant use multiple chart in same screen scrollview

### ISSUE THREAD

**Issue by MuthuSubramaniam** [AnyChart/AnyChart-Android#41]
I can't use multiple charts in single page using scrollview. If i use single then its view showing. If I use multiple then the view is not showing.

**Comment by Shestac92** [comment]
@MuthuSubramaniam 
Please, can you provide us your code to review it and suggest a proper solution?

**Comment by MuthuSubramaniam** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context=".MainActivity">

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">


        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:weightSum="4">

            <com.anychart.AnyChartView
                android:id="@+id/any_chart_view"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1" />

            <com.anychart.AnyChartView
                android:id="@+id/any_chart_view1"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1" />

            <com.anychart.AnyChartView
                android:id="@+id/any_chart_view2"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1" />

            <com.anychart.AnyChartView
                android:id="@+id/any_chart_view3"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1" />

        </LinearLayout>
    </ScrollView>


</LinearLayout>`

**Comment by MuthuSubramaniam** [comment]
`
        Pie pie = AnyChart.pie();

        List<DataEntry> data = new ArrayList<>();
        data.add(new ValueDataEntry("John", 10000));
        data.add(new ValueDataEntry("Jake", 12000));
        data.add(new ValueDataEntry("Peter", 18000));
     
        pie.data(data);

        AnyChartView anyChartView = (AnyChartView) findViewById(R.id.any_chart_view);
        anyChartView.setChart(pie);
 
       AnyChartView anyChartView1 = (AnyChartView) findViewById(R.id.any_chart_view1);
        anyChartView1.setChart(pie);
      .
      .
      .
      .
      .

    AnyChartView anyChartView5 = (AnyChartView) findViewById(R.id.any_chart_view5);
        anyChartView5.setChart(pie);
`

**Comment by Shestac92** [comment]
@MuthuSubramaniam 
thank you! 
Please, try the following approach:
```java
List<DataEntry> data = new ArrayList<>();
data.add(new ValueDataEntry("Apples", 6371664));
data.add(new ValueDataEntry("Pears", 789622));
data.add(new ValueDataEntry("Bananas", 7216301));
data.add(new ValueDataEntry("Grapes", 1486621));
data.add(new ValueDataEntry("Oranges", 1200000));

AnyChartView anyChartView = findViewById(R.id.any_chart_view);
APIlib.getInstance().setActiveAnyChartView(anyChartView);

Pie pie = AnyChart.pie();

pie.data(data);

anyChartView.setChart(pie);

AnyChartView anyChartView1 = findViewById(R.id.any_chart_view1);
APIlib.getInstance().setActiveAnyChartView(anyChartView1);

Pie pie1 = AnyChart.pie();

pie1.data(data);

anyChartView1.setChart(pie1);
```

**Comment by Poissac9** [comment]
It didn't work for me

**Comment by ZhaziraD** [comment]
Is there any other solution?
