### ISSUE TITLE
Line chart in Android caused a problem

### ISSUE THREAD

**Issue by shubhamphal** [AnyChart/AnyChart-Android#42]
E/TEST: Uncaught SyntaxError: missing ) after argument list

E/TEST: cartesian1 = anychart.line();cartesian1.animation(true);cartesian1.padding(10.0, 20.0, 5.0, 20.0);crosshair2 = cartesian1.crosshair();crosshair2.enabled(true);crosshair3 = cartesian1.crosshair();crosshair3.yLabel(true);crosshair3.yStroke(null, null, null, null, null);tooltip4 = cartesian1.tooltip();tooltip4.positionMode("point");cartesian1.title('SEMESTER-WISE GRADE POINT AVERAGE');linear5 = cartesian1.yAxis(0);linear5.title('SGPA');linear6 = cartesian1.xAxis(0);labelsFactory7 = linear6.labels();labelsFactory7.padding(5.0, 5.0, 5.0, 5.0);set8 = new anychart.data.set();set8.data([{value2: '8.0',x: '1',value: '9.4',value3: '10.0'},{value2: '9.2',x: '2',value: '9.2',value3: '9.92'},{value2: '9.3',x: '3',value: '9.44',value3: '9.8'},{value2: '8.5',x: '4',value: '9.46',value3: '9.84'}]);mapping9 = set8.mapAs({ x: 'x', value: 'value' });mapping10 = set8.mapAs({ x: 'x', value: 'value2' });mapping11 = set8.mapAs({ x: 'x', value: 'value3' });line12 = cartesian1.line(mapping9);line12.name('MY SGPA');stateSettings13 = line12.hovered();markersFactory14 = stateSettings13.markers();markersFactory14.enabled(true);stateSettings15 = line12.hovered();markersFactory16 = stateSettings15.markers();markersFactory16.type("circle");markersFactory16.size(4.0);tooltip17 = line12.tooltip();tooltip17.position('right');tooltip17.anchor("left-center");tooltip17.offsetX(5.0);tooltip17.offsetY(5.0);line18 = cartesian1.line(mapping10);line18.name('AVERAGE SGPA');stateSettings19 = line18.hovered();markersFactory20 = stateSettings19.markers();markersFactory20.enabled(true);stateSettings21 = line18.hovered();markersFactory22 = stateSettings21.markers();markersFactory22.type("circle");markersFactory22.size(4.0);tooltip23 = line18.tooltip();tooltip23.position('right');tooltip23.anchor("left-center");tooltip23.offsetX(5.0);tooltip23.offsetY(5.0);line24 = cartesian1.line(mapping11);line24.name('Topper's SGPA');stateSettings25 = line24.hovered();markersFactory26 = stateSettings25.markers();markersFactory26.enabled(true);stateSettings27 = line24.hovered();markersFactory28 = stateSettings27.markers();markersFactory28.type("circle");markersFactory28.size(4.0);tooltip29 = line24.tooltip();tooltip29.position('right');tooltip29.anchor("left-center");tooltip29.offsetX(5.0);tooltip29.offsetY(5.0);legend30 = cartesian1.legend();legend30.enabled(true);legend31 = cartesian1.legend();legend31.fontSize(13.0);legend32 = cartesian1.legend();legend32.padding(0.0, 0.0, 10.0, 0.0);

**Comment by imaximova** [comment]
Can you send the code, please?

**Comment by shubhamphal** [comment]
Sure here is the code snippet


/*code */
                    
                  AnyChartView anyChartView = prompt.findViewById(R.id.anychart_performance);
                    APIlib.getInstance().setActiveAnyChartView(anyChartView);

                    /*set progress bar*/
                    anyChartView.setProgressBar(prompt.findViewById(R.id.progress_bar));


                    Cartesian cartesian = AnyChart.line();

                    cartesian.animation(true);

                    cartesian.padding(10d, 20d, 5d, 20d);


                    cartesian.crosshair().enabled(true);
                    cartesian.crosshair()
                            .yLabel(true)
                            // TODO ystroke
                            .yStroke((Stroke) null, null, null, (String) null, (String) null);

                    cartesian.tooltip().positionMode(TooltipPositionMode.POINT);

                    cartesian.title("SEMESTER-WISE GRADE POINT AVERAGE");

                    cartesian.yAxis(0).title("SGPA");
                    cartesian.xAxis(0).labels().padding(5d, 5d, 5d, 5d);


                    List<DataEntry> seriesData = new ArrayList<>();


                    for (int i = 0; i < number_of_semesters; i++) {
                        int sem = i + 1;
                        seriesData.add(new CustomDataEntry("" + sem, studentsgpa[i], averagesgpa[i], toppersgpa[i]));

                    }

                    Set set = Set.instantiate();
                    set.data(seriesData);


                    Mapping series1Mapping = set.mapAs("{ x: 'x', value: 'value' }");
                    Mapping series2Mapping = set.mapAs("{ x: 'x', value: 'value2' }");
                    Mapping series3Mapping = set.mapAs("{ x: 'x', value: 'value3' }");

                    Line series1 = cartesian.line(series1Mapping);
                    series1.name("MY SGPA");
                    series1.hovered().markers().enabled(true);
                    series1.hovered().markers()
                            .type(MarkerType.CIRCLE)
                            .size(4d);
                    series1.tooltip()
                            .position("right")
                            .anchor(com.anychart.enums.Anchor.LEFT_CENTER)
                            .offsetX(5d)
                            .offsetY(5d);

                    Line series2 = cartesian.line(series2Mapping);
                    series2.name("AVERAGE SGPA");
                    series2.hovered().markers().enabled(true);
                    series2.hovered().markers()
                            .type(MarkerType.CIRCLE)
                            .size(4d);
                    series2.tooltip()
                            .position("right")
                            .anchor(com.anychart.enums.Anchor.LEFT_CENTER)
                            .offsetX(5d)
                            .offsetY(5d);

                    Line series3 = cartesian.line(series3Mapping);
                    series3.name("Topper's SGPA");
                    series3.hovered().markers().enabled(true);
                    series3.hovered().markers()
                            .type(MarkerType.CIRCLE)
                            .size(4d);
                    series3.tooltip()
                            .position("right")
                            .anchor(com.anychart.enums.Anchor.LEFT_CENTER)
                            .offsetX(5d)
                            .offsetY(5d);

                    cartesian.legend().enabled(true);
                    cartesian.legend().fontSize(13d);
                    cartesian.legend().padding(0d, 0d, 10d, 0d);


                    anyChartView.setChart(cartesian);
