### ISSUE TITLE
is there a callback method to find out that the chart loading and rendering is complete?

### ISSUE THREAD

**Issue by ihsanulhaq-saal-ai** [AnyChart/AnyChart-Android#43]
For large data, the chart rendering takes quite some time. How can we perform tasks with surety that the graph loading is indeed complete?

I believe if we modify the code a little and provide an interface that could be called from the JsListener in the `AnyChartView` class, this could be achieved. thoughts?

**Comment by imaximova** [comment]
Can you tell me what do you want to do after rendering the chart?

**Comment by ihsanulhaq-saal-ai** [comment]
I'd like to make other parts of the UI visible.
I have multiple charts on the same screen  and they all load at a different rate.
I'd like to present the user with a refresh button - but only once all the charts have successfully rendered.

**Comment by Shestac92** [comment]
@ihsanulhaq-saal-ai 
We have added a callback:
`anyChartView.setOnRenderedListener()`

Please, update your library version to enable it.

**Comment by ihsanulhaq-saal-ai** [comment]
You are awesome!!! Thanks!!

**Comment by ihsanulhaq-saal-ai** [comment]
any particular reason from bumping up the sdk version? i cant use this version anymore :( my app needs to support api 27.

**Comment by Shestac92** [comment]
@ihsanulhaq-saal-ai 
You can increase you `targetSdkVersion` up to the 28 version or add the following code to provide compatibility with the 27 version:
```
implementation ('com.github.AnyChart:AnyChart-Android:1.0.4') {
    exclude group: 'com.android.support'
}
```
