### ISSUE TITLE
Animation not working in circular gauge chart

### ISSUE THREAD

**Issue by lalitsharma1607** [AnyChart/AnyChart-Android#45]
Circular Gauge chart is having issue with animation. I tried using below method but it is not showing any animation.
        `circularGauge.animation(true, 3000)`

**Comment by Shestac92** [comment]
@lalitsharma1607 
Unfortunately, the current version of AnyChart library 8.3.0 doesn't provide animation for circular gauges.

**Comment by lalitsharma1607** [comment]
ok, Thanks @Shestac92
