### ISSUE TITLE
Unable to set Multiple Column chart in Single screen

### ISSUE THREAD

**Issue by KartikAggarwal** [AnyChart/AnyChart-Android#46]
Unable to set multiple column charts in single screen (ScrollView)

**Comment by Shestac92** [comment]
@KartikAggarwal 
Please, check [this article](https://github.com/AnyChart/AnyChart-Android/wiki/Multiple-charts-in-a-single-layout) which describes how to create multiple charts in a single layout.

**Comment by KartikAggarwal** [comment]
> @KartikAggarwal
> Please, check [this article](https://github.com/AnyChart/AnyChart-Android/wiki/Multiple-charts-in-a-single-layout) which describes how to create multiple charts in a single layout.

**Comment by KartikAggarwal** [comment]
> @KartikAggarwal
> Please, check [this article](https://github.com/AnyChart/AnyChart-Android/wiki/Multiple-charts-in-a-single-layout) which describes how to create multiple charts in a single layout.

Thanks Shestac92, I found the solution.
