### ISSUE TITLE
Realtime linechart?

### ISSUE THREAD

**Issue by hungvu193** [AnyChart/AnyChart-Android#47]
I want to update my line chart every 1 minute wit a few new values, how can i do that?

**Comment by Shestac92** [comment]
@hungvu193 
Please, try to use the approach described in [this issue](https://github.com/AnyChart/AnyChart-Android/issues/28) to update your line chart.

**Comment by hungvu193** [comment]
@Shestac92 thank you buddy, i will try and close this issue for now
