### ISSUE TITLE
How to refresh Pie chart without re-create "pie = AnyChart.pie();"

### ISSUE THREAD

**Issue by jvlichai** [AnyChart/AnyChart-Android#48]
How to refresh Pie chart without re-create "pie = AnyChart.pie();"

**Comment by jvlichai** [comment]
I have tried by not working. Could you test it out?

**Comment by Shestac92** [comment]
@jvlichai 
Thank you for your report! There was a typo.
Please, try the corrected sample [here.](https://gist.github.com/ArsenyMalkov/4f13aca9bdde09abd6547b2fde5bede6)

**Comment by jvlichai** [comment]
Great! It works. Thanks!
