### ISSUE TITLE
How to change background of Map in ChoroplethMap type chart? Also the background is always white. Is there a way to change that as well?

### ISSUE THREAD

**Issue by aadesh0118** [AnyChart/AnyChart-Android#53]

**Comment by aadesh0118** [comment]
Thanks this works. Also, is there a way to set the chart to a particular zoom level?

**Comment by Shestac92** [comment]
@aadesh0118 
Yes, there are several approaches for zooming the map to a particular zoom level and center. All of them are described in [this article](https://docs.anychart.com/Maps/Move_and_Zoom#zoom).

**Comment by aadesh0118** [comment]
Thanks. One more question. How do i give data in case of point map? I am using a js for asia.

    data.add(new CustomDataEntryMap("WL.AFG", "Afghanistan", "Afghanistan", 35.650072333309225,  61.21081709172574));

this is how i am adding data. But its not showing on map. As per your example you have given co-ordinates of cities. How am i supposed to give them for India and Indian cities?

Also, After i zoom in i want to disable the map movement when user drags. how can i do that?

**Comment by Shestac92** [comment]
@aadesh0118 
You can create a map with dot series like it is shown below. Just add India map and replace coordinates in the CustomDataEntry. 
```
        AnyChartView anyChartView = findViewById(R.id.any_chart_view);

        Map map = AnyChart.map();
        map.geoData("anychart.maps.united_states_of_america");

        Marker series = map.marker(getData());

        series.size(5)
                .labels(false)
                .stroke("2 #E1E1E1")
                .fill("#1976d2", 1)
                .selectionMode(SelectionMode.NONE);

        anyChartView.addScript("file:///android_asset/united_states_of_america.js");
        anyChartView.addScript("file:///android_asset/proj4.js");
        anyChartView.setChart(map);
    }

    private List<DataEntry> getData() {
        List<DataEntry> data = new ArrayList<>();

        data.add(new CustomDataEntry("BHM", "Birmingham", "Birmingham-Shuttlesworth International Airport", 33.5639, -86.7522));
        data.add(new CustomDataEntry("DHN", "Dothan", "Dothan Regional Airport", 31.3214, -85.4497));
        data.add(new CustomDataEntry("HSV", "Huntsville", "Huntsville International Airport", 34.6372, -86.775));
        data.add(new CustomDataEntry("MOB", "Mobile", "Mobile Regional Airport", 30.6914, -88.2428));
        data.add(new CustomDataEntry("MLI", "Moline", "Quad City International Airport", 41.4486, -90.5072));

        return data;
    }

    class CustomDataEntry extends DataEntry {
        public CustomDataEntry(String id, String city, String name, Double latitude, Double longitude) {
            setValue("id", id);
            setValue("city", city);
            setValue("name", name);
            setValue("lat", latitude);
            setValue("long", longitude);
        }
    }
```

**Comment by aadesh0118** [comment]
I have created a JS file for asia. And added that from assets folder. How am i supposed to use that?

That map does not have co ordinates for respective cities rather they have different countries.

**Comment by Shestac92** [comment]
@aadesh0118 
Please, can you specify which cities do you want to point on the map?

**Comment by Shestac92** [comment]
@aadesh0118 
Thank you for the map, now I see your issue. The problem is that this map provides wrong coordinates and relative shape of regions. It means that if you set real coordinates of Delhi, you won't see a point on this map. We can provide you with a correct map of the Asia region. Please, provide us with a list of required countries and we will prepare the map.

**Comment by aadesh0118** [comment]
Thank you so much for your help. The countries i need are:
India, Pakistan, Afghanistan, Iran, Sri Lanka, Nepal, Bhutan, China, Bangladesh,Myanmar,Tajikistan,Turkmenistan

**Comment by Shestac92** [comment]
@aadesh0118 
Ok, we will prepare the map. It will take some time, approximately during 24 hours you will receive the map.

**Comment by Shestac92** [comment]
@aadesh0118 
We have prepared a custom-made map of Asian region according to your country list. You can download the map using [this link](http://cdn.anychart.com/ts/asia.js).
The map name is `asia`, as geoIdField use `code_hasc`.

**Comment by aadesh0118** [comment]
Thanks very much for the map. Could you please tell me how can i disable the dragging of map by user's touch? I have zoomed the map to a certain level and i want user to see that portion only. So i need to disable the drag.

**Comment by Shestac92** [comment]
@aadesh0118 
Yes, you can disable drugging in the map interactivity settings like this:
```
map.interactivity().drag(false);
```

**Comment by aadesh0118** [comment]
One last question. In the point map when there are a lot of points it becomes cluttered. Is there a feature of clustering in the map so that the points the are too close to each other can be shown as a single point? 
Thanks.

**Comment by Shestac92** [comment]
@aadesh0118 
Unfortunately, the current version of AnyChart library 8.4.1 doesn't provide grouping points on a map. But probably, we can add zooming feature for a map to enable zooming the clicked region. This feature is available in the web version of AnyChart library.

**Comment by aadesh0118** [comment]
Thanks for your help.
