### ISSUE TITLE
AnyChart in App Widget

### ISSUE THREAD

**Issue by edof** [AnyChart/AnyChart-Android#54]
Can I show AnyChart in App Widget?
I've tried show it but the chart is not showing. just show an error loading widget

**Comment by Shestac92** [comment]
@edof 
Unfortunately, there's no possibility to use AnyChart view as app widget. It comes from the strict list of classes available for use in app widget. Official documentation says: `App Widget layouts are based on RemoteViews, which do not support every kind of layout or view widget.`

**Comment by edof** [comment]
@Shestac92 
sorry for my late reply. I see, it can't be used as app widget. thank you for your answer.
I will close this issue.
