### ISSUE TITLE
Redrawing the PIE CHART

### ISSUE THREAD

**Issue by bowiechang** [AnyChart/AnyChart-Android#56]
Firstly thank you for the lovely project, wonderful piece of work.

I would like to redraw the pie chart after user selects a new set of data to show on the chart but apparently, so i set a new list into the chart but the thing is, it just disappears. Please kindly discuss about this with me thanks in advance! Hope to hear from you.

**Comment by Shestac92** [comment]
@bowiechang 
Please, check [this sample ](https://gist.github.com/ArsenyMalkov/4f13aca9bdde09abd6547b2fde5bede6) which describes how to update the pie chart with new data. This should work.

**Comment by fakefacebook** [comment]
i am confusing in redrawing column chart can any one help?

**Comment by Shestac92** [comment]
@fakefacebook 
[This issue comment ](https://github.com/AnyChart/AnyChart-Android/issues/28#issuecomment-417997179)should help you to update the column chart. Does it work for you?
