### ISSUE TITLE
Redrawing the ColumnChart not working

### ISSUE THREAD

**Issue by fakefacebook** [AnyChart/AnyChart-Android#57]
add new data after load in ColumnChart is not works

```
 data.add(new ValueDataEntry("Eyeshadows", 249980));
                cartesian.column(data);
                anyChartView.setChart(cartesian);

```
not worked it shows blank

                anyChartView.invalidate();
is also not works

**Comment by Shestac92** [comment]
@fakefacebook 
Please, check [this issue comment](https://github.com/AnyChart/AnyChart-Android/issues/28#issuecomment-417997179). It describes the approach of how to update the chart with new data.
