### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Vivektilva** [AnyChart/AnyChart-Android#6]
@Shestac92 

Thank you so much for your all support,
I have one query ,

I just want to use this funnel chart in my app and want to publish this app to play store, 
Do I need to buy paid version or free version will work ???

**Comment by loki20beta** [comment]
@Vivektilva you can use for free only in the non-commercial application, please email to sales@anychart.com to learn more

**Comment by Vivektilva** [comment]
Thank you for information @loki20beta

**Comment by loki20beta** [comment]
@Vivektilva you are welcome.
