### ISSUE TITLE
Memory Leak Problem

### ISSUE THREAD

**Issue by aldiand** [AnyChart/AnyChart-Android#63]
AnyChartView have memory leak issue, on onRestoreInstanceState.

```
    public void onRestoreInstanceState(Parcelable state) {
        if (state instanceof Bundle) {
            Bundle bundle = (Bundle) state;
            **this.js.append(bundle.getString("js"));**
            state = bundle.getParcelable("superState");
        }
        isRestored = true;

        super.onRestoreInstanceState(state);
    }
```
if activity fragment restored multiple times, StringBuilder this.js will doubled.
Please fix this

**Comment by ArsenyMalkov** [comment]
Thank you for your report. It will be fixed.

**Comment by aldiand** [comment]
The fixes only take 1 line of code 😃

**Comment by ArsenyMalkov** [comment]
Not exactly. In this case, dynamic data will not work after orientation change. Your fix will work only for charts that already rendered and will not for those which have any changes after a chart is rendered.

**Comment by aldiand** [comment]
Thank you for fast support
