### ISSUE TITLE
Unable to create Map after updating from 0.30 to 1.0.8 version.

### ISSUE THREAD

**Issue by aadesh0118** [AnyChart/AnyChart-Android#64]
I recently changed the version of the library. And also changed the code accordingly. 

I was able to display the map in the last version. But in this version it is empty. I don't understand where am i doing wrong. Here is the code: 

     Map map = AnyChart.map();
        
        chartRegionView.setZoomEnabled(false);
        chartRegionView.setEnabled(false);

      //  map.removeSeriesAt(0);
        //  chartRegionView.removeViewAt(0);

        if (AxesTrackApplication.getThemenew(context) == 0) {

            map.background("#292A35");

            map.unboundRegions()
                    .enabled(true)
                    .fill("#385454", 1)
                    .stroke("#385454");
        } else {
            map.background("#DAEDED");

            map.unboundRegions()
                    .enabled(true)
                    .fill("#78B3C0", 1)
                    .stroke("#78B3C0");
        }

        map.geoData("anychart.maps.asia");
        map.interactivity().drag(false);

        Marker series = map.marker(getDataMap());

        series.tooltip()
                .useHtml(true)
                .padding(8, 13, 10, 13)
                .title(false)
                .fontSize(14)
                .format("function() {\n" +
                        "            return '<span>' + this.getData('name') + '</span><br/>' +\n" +
                        "              '<span style=\"font-size: 12px; color: #E1E1E1\">City: ' +\n" +
                        "              this.getData('city') + '</span>';\n" +
                        "          }");

        series.tooltip(false);

        series.size(5)
                .labels(false);

        if (AxesTrackApplication.getThemenew(context) == 0) {
            series.stroke("2 #E1E1E1")
                    .fill("#1976d2", 1);
        } else {
            series.stroke("2 #E1E1E1")
                    .fill("#1976d2", 1);
        }

        series.selectionMode(SelectionMode.NONE);

       // map.zoomTo(2, 100, 100);

        chartRegionView.addScript("file:///android_asset/asiaaa.js");

        chartRegionView.addScript("file:///android_asset/proj4.js");

        //map.zoom(7,0,0,1);

        //map.move(300,0);

        LogUtils.debug("DashboardMAp", "Creating chart");

        
        chartRegionView.setChart(map);

**Comment by ArsenyMalkov** [comment]
I don't see the problem in your code. So I suppose something wrong with your map. Are you using anychart geo map?

**Comment by aadesh0118** [comment]
Yes in fact i am using the map which was provided by you guys in a previous issue. 

Also, the map was completely fine in the previous version. This problem appeared only after i updated the library to the latest version.

**Comment by ArsenyMalkov** [comment]
Ok, I have found that map. I think the problem may be that map names are not the same

Try to change the name in geodata
```java
map.geoData("anychart.maps.asiaaa");

chartRegionView.addScript("file:///android_asset/asiaaa.js");
```
or rename the map in assets to "asia.js"
```java
map.geoData("anychart.maps.asia");

chartRegionView.addScript("file:///android_asset/asia.js");
```

**Comment by aadesh0118** [comment]
This is the model class which is used to create the map

    [public class DashboardMapChart {

    AnyChartView chartRegionView;
    private ArrayList<VehicleInfo> vehiclelist;
    private ProgressBar progressBar;
    private ImageView strip;
    private Context context;

    public DashboardMapChart(AnyChartView chartRegionView, ArrayList<VehicleInfo> vehiclelist, ProgressBar progressBar, ImageView strip, Context context) {
        this.chartRegionView = chartRegionView;
        this.vehiclelist = vehiclelist;

        this.progressBar = progressBar;
        this.strip = strip;
        this.context = context;
    }

    public void createMap() {


        Map map = AnyChart.map();

        chartRegionView.setZoomEnabled(false);
        chartRegionView.setEnabled(false);


      //  map.removeSeriesAt(0);
        //  chartRegionView.removeViewAt(0);

        if (AxesTrackApplication.getThemenew(context) == 0) {

            map.background("#292A35");


            map.unboundRegions()
                    .enabled(true)
                    .fill("#385454", 1)
                    .stroke("#385454");
        } else {
            map.background("#DAEDED");


            map.unboundRegions()
                    .enabled(true)
                    .fill("#78B3C0", 1)
                    .stroke("#78B3C0");
        }

        map.geoData("anychart.maps.asiaaa");
        map.interactivity().drag(false);




        Marker series = map.marker(getDataMap());


        series.tooltip()
                .useHtml(true)
                .padding(8, 13, 10, 13)
                .title(false)
                .fontSize(14)
                .format("function() {\n" +
                        "            return '<span>' + this.getData('name') + '</span><br/>' +\n" +
                        "              '<span style=\"font-size: 12px; color: #E1E1E1\">City: ' +\n" +
                        "              this.getData('city') + '</span>';\n" +
                        "          }");

        series.tooltip(false);

        series.size(5)
                .labels(false);

        if (AxesTrackApplication.getThemenew(context) == 0) {
            series.stroke("2 #E1E1E1")
                    .fill("#1976d2", 1);
        } else {
            series.stroke("2 #E1E1E1")
                    .fill("#1976d2", 1);
        }


        series.selectionMode(SelectionMode.NONE);


       // map.zoomTo(2, 100, 100);

        chartRegionView.addScript("file:///android_asset/asiaaa.js");

        chartRegionView.addScript("file:///android_asset/proj4.js");


        //map.zoom(7,0,0,1);


        //map.move(300,0);

        LogUtils.debug("DashboardMAp", "Creating chart");


        chartRegionView.setChart(map);


        DashboardActivity.created = true;

        progressBar.setVisibility(View.GONE);
        chartRegionView.setVisibility(View.VISIBLE);
        strip.setVisibility(View.VISIBLE);


    }

    private List<DataEntry> getDataMap() {
        List<DataEntry> data = new ArrayList<>();

        for (int i = 0; i < vehiclelist.size(); i++) {
            try {
                data.add(new CustomDataEntryMap("BHM", "Birmingham", "Birmingham-Shuttlesworth International Airport", Double.parseDouble(vehiclelist.get(i).getLatitude()),
                        Double.parseDouble(vehiclelist.get(i).getLongitude())));
            }catch (NumberFormatException e){

            }

        }

     return data;
    }

    class CustomDataEntryMap extends DataEntry {
        public CustomDataEntryMap(String id, String city, String name, Double latitude, Double longitude) {
            setValue("id", id);
            setValue("city", city);
            setValue("name", name);
            setValue("lat", latitude);
            setValue("long", longitude);
        }

        public CustomDataEntryMap(String id, String name, Number value, String color) {
            setValue("id", id);
            setValue("name", name);
            setValue("value", value);
            setValue("fill", color);
        }
    }
    }


My layout contains multiple cards. One of the cards has the map.

XML  is : 

     <android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/regions_chart_card"
    android:layout_width="match_parent"
    android:layout_height="250dp"
    android:layout_margin="5dp"
    android:layout_marginTop="10dp"
    app:cardBackgroundColor="#31323F"
    app:cardCornerRadius="5dp">

    <LinearLayout
        android:id="@+id/linear_layout_map"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="0.2"
            android:background="#292A35"
            android:gravity="center"
            android:text="Vehicle Map"
            android:textSize="12sp"
            android:textStyle="bold"
            android:textAlignment="center"
            android:textAllCaps="true"
            android:textColor="#ffffff" />

        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="219dp"
            android:background="#31323F"
            android:orientation="vertical">


            <com.anychart.AnyChartView
                android:id="@+id/region_chart"
                android:visibility="gone"
                android:layout_width="match_parent"
                android:layout_height="219dp" />


          


            

            <ProgressBar
                android:id="@+id/progress_bar_region"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />


        </FrameLayout>

    </LinearLayout>


    </android.support.v7.widget.CardView>

**Comment by ArsenyMalkov** [comment]
Your layout and code above are ok.

Is your card view used in a recycler view? Also, could you check that vehiclelist is not empty? Just to make sure.

**Comment by aadesh0118** [comment]
The vehicle list is not empty i have checked it.

And i have a scrollview with multiple cards. One of the card is the map.

**Comment by ArsenyMalkov** [comment]
Update project to 1.0.9. Then set debug to true `chartRegionView.setDebug(true);` and show your log by tag "AnyChart".

**Comment by aadesh0118** [comment]
This is the error :  

    Uncaught ReferenceError: map3 is not defined

**Comment by ArsenyMalkov** [comment]
If this is acceptable to you, could you provide the entire project? So it will be easier and faster to investigate the issue.

**Comment by aadesh0118** [comment]
My apologies.. I do not have the authority to share the entire project.

**Comment by aadesh0118** [comment]
https://gist.github.com/aadesh0118/758b756b8e986f382b83dacb4450561d

this is the map that i am using. it was working with version 0.3.0 of the library.

**Comment by ArsenyMalkov** [comment]
Ok.
First about geoData. It should be `map.geoData("anychart.maps.asia");` because this name is used in your map js file and it does not depend on an actual file name. Anyway, your problem is not in that.

I recreated your code and layout and checked your map. I haven't faced any problems. Thus your map file is not the root of the issue.

Does the log contain any other AnyChart errors except `map3`?

Could you provide the code of activity for the model class and xml layout where the ScrollView is used?

**Comment by aadesh0118** [comment]
this is the main layout:
https://gist.github.com/aadesh0118/4d96ffc3c5e4478b5cd8c22d766340c5

This is the activity: 
https://gist.github.com/aadesh0118/b0482df8e7cf4af41d3924400ca3a2cb

The model(DashboardMapChart ) is set from the handler.

**Comment by aadesh0118** [comment]
this is the javascript evaluated

    evaluateJavascript=anychart.licenseKey("");anychart.onDocumentReady(function () {
    map3.container("container");map3.draw();});

And after this there is an error that map3 is not defined

**Comment by aadesh0118** [comment]
Yes finally it works. Thanks man you are a legend.
