### ISSUE TITLE
Dynamic data chart

### ISSUE THREAD

**Issue by ronzierLoic** [AnyChart/AnyChart-Android#68]
Hello, 

Is it possible to make a **dynamic data chart** (**stock Line**) ? 

And what is the **minimal delay** to refresh the data chart ?

Last question, is it possible to add **line** in the **stock scroller** in the next release ?

Thanks for your support !

**Comment by Shestac92** [comment]
@ronzierLoic 
Yes, it's possible!
The Stock chart based on data tables. The dataTable provides `addData()` function to add new data. You can use this function after the chart was rendered. Just execute `table.addData({data})`.
The `data` should be similar to the Android style, like this:
```
List<DataEntry> data = new ArrayList<>();
data.add(new OHCLDataEntry(638380800000L,0.0825,0.0842,0.0816,0.0842));
table.addData(data);
```
The minimal delay depends on available resources.
We have just added a line series to the scroller. Please, update the library up to the latest 1.1.2 version.
