### ISSUE TITLE
How to change language pop- up message when clicked graph 

### ISSUE THREAD

**Issue by ytam** [AnyChart/AnyChart-Android#7]
![screenshot_1519820491 - kopya](https://user-images.githubusercontent.com/15671434/36787712-1dce56c0-1c9c-11e8-94d9-3ad8775aaa1e.png)

**Comment by loki20beta** [comment]
@ytam 

1) use getTooltip() here is a sample in marker series that does something similar https://github.com/AnyChart/AnyChart-Android/blob/master/sample/src/main/java/com/anychart/sample/charts/ScatterChartActivity.java#L67

2) to change the trial text you need to purchase a license and then apply a license key and then you will be able to disable the credits. Please email to sales@anychart.com to get a proper quote.

**Comment by ytam** [comment]
There will be a problem when use library with that text and use library without license

**Comment by loki20beta** [comment]
@ytam you can use the trial version for testing or during the development phase. 

Publishing a commercial application without the proper license constitutes the breach of the license agreement and a copyright infringement.

**Comment by ytam** [comment]
Ok. Thank you, I sent mail to sale email address
