### ISSUE TITLE
Format X axis labels

### ISSUE THREAD

**Issue by pinicius** [AnyChart/AnyChart-Android#72]
Hi,
I have a dataset created dinamically with dates (date + time) printed on X axis. Sometimes dates have the same date but different time, how can I format x label to show only the date?

Thanks in advance!

**Comment by Shestac92** [comment]
@pinicius 
You can achieve that using string tokens like this:
```
xAxis.labels().format('{%value}{dateTimeFormat:yyyy-MM-dd}');
```
You can define your own dateTime patter.

**Comment by pinicius** [comment]
Thanks very much @Shestac92
