### ISSUE TITLE
How to display  percent sign (%)?

### ISSUE THREAD

**Issue by whruiqlik** [AnyChart/AnyChart-Android#74]
Please tell me how to display percent sign (%). Thank you.
0.7 --> 70%

![20190215091932](https://user-images.githubusercontent.com/43289168/52828415-aab28580-3103-11e9-9a45-95816876009c.png)

**Comment by Shestac92** [comment]
You can achieve that using the same string token in the labels formatter like this:
```
series.labels().format('{%value}%');
```

**Comment by whruiqlik** [comment]
@Shestac92 
I copied it into Data Lables, but the result wasn't what I wanted.

![20190218122256](https://user-images.githubusercontent.com/43289168/52930366-13f3fc00-3383-11e9-9904-195b5d6a6d3d.png)

**Comment by Shestac92** [comment]
@whruiqlik 
Excuse me, I got your idea in the wrong way in the beginning. 
You can achieve that using special token. Please, try the following token for Data Labels:
`{%yPercentOfCategory}%}

**Comment by whruiqlik** [comment]
Thank you. It's okay to use it in Staked Bar Chart, but it's okay to use it in Combo Chart.
Please look at the picture.Thank you.
![ok1](https://user-images.githubusercontent.com/43289168/53010136-0c624f00-3478-11e9-8619-086d98979f0b.png)
![a1](https://user-images.githubusercontent.com/43289168/53010142-11270300-3478-11e9-8457-f752275b2736.png)
![a2](https://user-images.githubusercontent.com/43289168/53010145-13895d00-3478-11e9-9b7f-b04aa05c3398.png)

**Comment by whruiqlik** [comment]
How can this problem be solved?
"it's no OK to use it in Combo Chart."

**Comment by Shestac92** [comment]
@whruiqlik 
Excuse me for the late reply.
As I can see from the screenshot the pink line represents points related to the yAxis on the right side. What values should the label show?
Please, correct me I got your idea in a wrong way. For example, the first point of the line series has a value of 0.8 and it's related to the yAxis on the right side. Should it show the label '0.8 %'?
If so, you can add the following token `{%value}%`

**Comment by whruiqlik** [comment]
I want to show percentages in the composite chart. For example, 0.8 - > 80%.
But I can't succeed in trying the following methods.

**{%Value} --> 0.8**
![1](https://user-images.githubusercontent.com/43289168/53407355-fc59ea80-39f6-11e9-9d20-0a1e58fef199.png)

**{%yPercentOfCategory}%  --> 1.05%**
![2](https://user-images.githubusercontent.com/43289168/53407376-054abc00-39f7-11e9-8156-a61e052b92a9.png)

**Comment by Shestac92** [comment]
@whruiqlik 
Unfortunately, for this purpose, there's no token to recalculate value to the percentage. You should preprocess the value before applying it to the chart.
All available options you can check in [this article](https://docs.anychart.com/Common_Settings/Text_Formatters#tokens_list).

**Comment by whruiqlik** [comment]
I used {% value} {decimalsCount: 1} and multiplied the data by 100, but the exported data was also multiplied by 100. How can I export normal data?

![1](https://user-images.githubusercontent.com/43289168/53873393-41a39b00-403b-11e9-97ee-bd508b4fe678.png)
![2](https://user-images.githubusercontent.com/43289168/53873402-45cfb880-403b-11e9-8339-0d4dd1081c0e.png)

**Comment by Shestac92** [comment]
@whruiqlik 
This is normal behavior. The series is connected to the scale on the right side of the chart. You can adjust the series position by applying this scale min/max values manually. Your series doesn't include negative values, so, there's no need in scale min -100%.
In "scales" tab adjust the scale min/max value to adjust the series position on the chart.

**Comment by whruiqlik** [comment]
Thank you!  How can I export the correct data?
![20190312184802](https://user-images.githubusercontent.com/43289168/54194551-7611ce00-44f7-11e9-8dfc-c2638bf19dfb.jpg)

**Comment by Shestac92** [comment]
@whruiqlik 
I'm afraid I have lost the flow of the issue.
This screenshot is from an Excel document? Was it exported from Qlik Sense?
What are the raw values of "Achieving %" column? According to the chart, the first value should be 54.76

**Comment by whruiqlik** [comment]
Please look at the pictures below. Please help me. Thank you.

![111111111](https://user-images.githubusercontent.com/43289168/54273187-509cc700-45c0-11e9-9771-394c1b846f4f.png)

**Comment by Shestac92** [comment]
@whruiqlik 
Do you multiply the raw value in the expression function?
I'm afraid you should turn to the Qlik Support regarding export data to excel. The exporting feature is provided by Qlik Sense, the AnyChart extension can't affect the data in the Qlik table.

**Comment by whruiqlik** [comment]
When I was looking for ways in XXX, I found the same problem there.
I don't know how to solve this problem.


![A1](https://user-images.githubusercontent.com/43289168/54328528-33600b00-4649-11e9-878e-c1490b572462.png)

![B1](https://user-images.githubusercontent.com/43289168/54328533-3824bf00-4649-11e9-8bcd-7ead032c97e4.png)

**Comment by Shestac92** [comment]
@whruiqlik 
I'm afraid we miss something on this issue. [The sample from the docs ](https://playground.anychart.com/docs/v8/samples/CS_format_01)you provided in your previous comment provides the following xlsx with correct values:
![Screenshot 2019-03-18 at 11 32 47](https://user-images.githubusercontent.com/24609062/54505127-95827e00-4971-11e9-8256-60a4ae10bd8b.png)

Do you implement the format conversion by yourself then?

**Comment by whruiqlik** [comment]
How can I add a percentage sign？

![20190404183611](https://user-images.githubusercontent.com/43289168/55549889-82a9d080-5709-11e9-9f3f-dd67330ab714.png)

**Comment by Shestac92** [comment]
@whruiqlik 
Unfortunately, the exporting function provides only raw values (numbers as integer) without formatting or additional symbols.

**Comment by whruiqlik** [comment]
ok, Thank you.
