### ISSUE TITLE
How to update data for map chart

### ISSUE THREAD

**Issue by MrRefactoring** [AnyChart/AnyChart-Android#75]
Hello! I use `AnyChart` with `Kotlin`.

To update `Cartesian` charts I used the following pseudocode:

```kotlin
lateinit var chartCanvas: Cartesian

fun initChart() {
  this.chartCanvas = AnyChart.line()

  ... // settings for chartCanvas
  chartCanvas.autoDraw()

  val anyChartView = view!!.findViewById(R.id.any_chart_view) as AnyChartView
  anyChartView.setChart(chartCanvas)
}

fun updateChartData(data: List<DataEntry>) {
  this.chartCanvas.data(data)
}
```

Now I need to do the same functionality for the `Map` chart

I tried to use something like this:

```kotlin
lateinit var chartCanvas: Map

fun initChart() {
  this.chartCanvas = AnyChart.map()

  ... // settings for chartCanvas
  val series = this.chartCanvas.choropleth(listOf())
  chartCanvas.autoDraw()

  val anyChartView = view!!.findViewById(R.id.any_chart_view) as AnyChartView

  anyChartView.addScript("file:///android_asset/united_states_of_america.js")
  anyChartView.addScript("file:///android_asset/proj4.js")

  anyChartView.setChart(chartCanvas)
}

fun updateChartData(data: List<DataEntry>) {
  this.chartCanvas.choropleth(data) // not working
}
```

But the chart is not updated. I tried to find any references in the documentation and go through the debugger on the source code, but it didn’t help much in my progress. I would be very grateful if you tell me a solution to this problem.

**Comment by Shestac92** [comment]
@MrRefactoring 
In the code, you have created a choropleth series on the map. You should update the data of this existing series.
`this.chartCanvas.choropleth(data)` - it doesn't update the series, it creates a new one.
You can update the series like this:
`series.data(data)`

**Comment by MrRefactoring** [comment]
@Shestac92 Thanks, it helped!

It turns out that with such a line the chart is not drawn. Be sure to specify a non-empty listOf.

```kotlin
this.series = chartCanvas.choropleth(listOf())
```
