### ISSUE TITLE
Line Chart y-axis with text labels

### ISSUE THREAD

**Issue by joseRelvasF3m** [AnyChart/AnyChart-Android#76]
I've tried many things, but I can't reach the following result:

![image](https://user-images.githubusercontent.com/46492808/52951016-9f1bc480-3378-11e9-8d45-e9574249e328.png)

Is there some way to introduce label text in y-axis?
Thank you.

**Comment by Shestac92** [comment]
@joseRelvasF3m 
We need a few details about the required chart. Is the yScale linear or just a categorized?
Is the interval between every y-tick the same?

**Comment by joseRelvasF3m** [comment]
Hi @Shestac92 . The graphic I'd shown is not made in AnyChart. I just wanna know if it is possible to put static labels in the y-axis, I don't get your question. Thank you!

**Comment by Shestac92** [comment]
@joseRelvasF3m 
Yes, it's possible! Please, check [this sample](https://playground.anychart.com/6lFzpmpT) for details.
