### ISSUE TITLE
How to reload Column Chart with new data? 

### ISSUE THREAD

**Issue by TalitaRamos** [AnyChart/AnyChart-Android#79]
Hi,

I'm using trial version, how to reload Column Chart with new data?

Thanks!

**Comment by Shestac92** [comment]
@TalitaRamos 
You can update the char column chart data the way what is shown in [this issue comment](https://github.com/AnyChart/AnyChart-Android/issues/28#issuecomment-417997179).

**Comment by TalitaRamos** [comment]
Thanks for the help.
I have modified the code but I still can not update the data.
``public class RendaFragment extends Fragment implements AdapterView.OnItemSelectedListener {

    private AnyChartView anyChartView;
    private Set set;

    public RendaFragment() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.fragment_renda, container, false);

        anyChartView = rootView.findViewById(R.id.any_chart_view_renda);
        anyChartView.setProgressBar(rootView.findViewById(R.id.progress_bar_renda));

        List<String> periodos = new ArrayList<String>();
        periodos.add("Semanalmente");
        periodos.add("Quinzenalmente");
        periodos.add("Mensalmente");

        Spinner spinnerPeriodo = rootView.findViewById(R.id.spinnerPeriodo);
        ArrayAdapter<String> adapter = new ArrayAdapter<String>(this.getActivity(), android.R.layout.simple_spinner_item, periodos);
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        spinnerPeriodo.setAdapter(adapter);
        spinnerPeriodo.setOnItemSelectedListener(this);

        Cartesian cartesian = AnyChart.column();

        List<DataEntry> data = new ArrayList<>();
        data.add(new ValueDataEntry("Pirão de Aipim", 30));
        data.add(new ValueDataEntry("Feijão Tropeiro", 50));
        data.add(new ValueDataEntry("Omelete", 120));
        data.add(new ValueDataEntry("Carne Moída", 30));
        data.add(new ValueDataEntry("Lasanha", 10));

        set = Set.instantiate();
        set.data(data);
        Mapping series1Data = set.mapAs("{ x: 'x', value: 'value' }");

        Column column = cartesian.column(series1Data);

        column.tooltip()
                .titleFormat("{%X}")
                .position(Position.CENTER_BOTTOM)
                .anchor(Anchor.CENTER_BOTTOM)
                .offsetX(0d)
                .offsetY(5d)
                .format("R${%Value}{groupsSeparator: }");

        cartesian.animation(true);
       // cartesian.title("Pratos mais pedidos");

        cartesian.yScale().minimum(0d);

        cartesian.yAxis(0).labels().format("R${%Value}{groupsSeparator: }");

        cartesian.tooltip().positionMode(TooltipPositionMode.POINT);
        cartesian.interactivity().hoverMode(HoverMode.BY_X);

        cartesian.xAxis(0).title("Prato");
        cartesian.yAxis(0).title("Rendimento total");

        anyChartView.setChart(cartesian);

        return rootView;
    }

    @Override
    public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
        String item = parent.getItemAtPosition(position).toString();
        if(item.equals("Semanalmente")){

            List<DataEntry> data1 = new ArrayList<>();
            data1.add(new ValueDataEntry("Pirão de Aipim", 30));
            data1.add(new ValueDataEntry("Feijão Tropeiro", 50));
            data1.add(new ValueDataEntry("Omelete", 120));
            data1.add(new ValueDataEntry("Carne Moída", 30));
            data1.add(new ValueDataEntry("Lasanha", 10));

            set.data(data1);

        }else if(item.equals("Quinzenalmente")){

            List<DataEntry> data2 = new ArrayList<>();
            data2.add(new ValueDataEntry("Pirão de Aipim", 60));
            data2.add(new ValueDataEntry("Feijão Tropeiro", 100));
            data2.add(new ValueDataEntry("Omelete", 240));
            data2.add(new ValueDataEntry("Carne Moída", 60));
            data2.add(new ValueDataEntry("Lasanha", 20));
            set.data(data2);

        }else if(item.equals("Mensalmente")){

            List<DataEntry> data3 = new ArrayList<>();
            data3.add(new ValueDataEntry("Pirão de Aipim", 90));
            data3.add(new ValueDataEntry("Feijão Tropeiro", 150));
            data3.add(new ValueDataEntry("Omelete", 360));
            data3.add(new ValueDataEntry("Carne Moída", 90));
            data3.add(new ValueDataEntry("Lasanha", 30));
            set.data(data3);
        }
        Toast.makeText(parent.getContext(), "Selected: " + item, Toast.LENGTH_LONG).show();
    }
    public void onNothingSelected(AdapterView<?> arg0) {
        // TODO Auto-generated method stub
    }
}``

**Comment by Shestac92** [comment]
@TalitaRamos 
Do you get any errors during building the application? Or it just doesn't update the chart data?

**Comment by TalitaRamos** [comment]
Hello! I was not updating but I managed to solve by removing the line below.

`Toast.makeText(parent.getContext(), "Selected: " + item, Toast.LENGTH_LONG).show();`
 
Thank you.

**Comment by herou** [comment]
>    List<DataEntry> data2 = new ArrayList<>();
>         data2.add(new ValueDataEntry("Pirão de Aipim", 60));
>         data2.add(new ValueDataEntry("Feijão Tropeiro", 100));
>         data2.add(new ValueDataEntry("Omelete", 240));
>         data2.add(new ValueDataEntry("Carne Moída", 60));
>         data2.add(new ValueDataEntry("Lasanha", 20));
>         set.data(data2);

This example helped me a lot, thank you <3
