### ISSUE TITLE
Graph Color ,legend label & Footer Image 

### ISSUE THREAD

**Issue by 1007047** [AnyChart/AnyChart-Android#8]
1.Graph color not customize
2.Legend label not changes
3.Footer image not hide.

**Comment by loki20beta** [comment]
@1007047 please share your code and screenshot so we could see what is wrong.

**Comment by 1007047** [comment]
![oie_sm5k8fa4gke1](https://user-images.githubusercontent.com/10253710/37073260-f32004c4-21ef-11e8-938e-ff01481c21c5.png)


Code :+1: 

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;

import com.anychart.anychart.AnyChart;
import com.anychart.anychart.AnyChartView;
import com.anychart.anychart.ChartsPolar;
import com.anychart.anychart.DataEntry;
import com.anychart.anychart.Mapping;
import com.anychart.anychart.PolarSeriesType;
import com.anychart.anychart.ScaleTypes;
import com.anychart.anychart.Set;
import com.anychart.anychart.TooltipDisplayMode;
import com.anychart.anychart.ValueDataEntry;
import com.pistrategy.android.iml.R;

import java.util.ArrayList;
import java.util.List;

public class PolarChartActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_polar_chart);

        AnyChartView anyChartView = findViewById(R.id.any_chart_view);

        ChartsPolar polar = AnyChart.polar();

        List<DataEntry> data = new ArrayList<>();
        data.add(new CustomDataEntry("Dhaka", 12814));

        data.add(new CustomDataEntry("Rajshai", 11399));
        data.add(new CustomDataEntry("Gazipur", 10399));
        data.add(new CustomDataEntry("Dinajpur", 9399));
        data.add(new CustomDataEntry("Lalmonirhat", 8399));
        data.add(new CustomDataEntry("Gaibandha", 7399));
        data.add(new CustomDataEntry("Khulna", 3232));
        data.add(new CustomDataEntry("Jessore", 2232));
        data.add(new CustomDataEntry("Barisal", 1832));
        data.add(new CustomDataEntry("Nilphamari", 1045));

      /*  data.add(new CustomDataEntry("Eyebrow pencil", 13012, 3987, 3932));
        data.add(new CustomDataEntry("Rouge", 11624, 3574, 5221));
        data.add(new CustomDataEntry("Pomade", 8814, 4376, 9256));
        data.add(new CustomDataEntry("Eyeshadows", 12998, 4572, 3308));
        data.add(new CustomDataEntry("Eyeliner", 12321, 3417, 5432));
        data.add(new CustomDataEntry("Foundation", 10342, 5231, 13701));
        data.add(new CustomDataEntry("Lip gloss", 22998, 4572, 4008));
        data.add(new CustomDataEntry("Mascara", 11261, 6134, 18712));
        data.add(new CustomDataEntry("Powder", 10261, 5134, 25712));
*/
        Set set = new Set(data);
        Mapping series1Data = set.mapAs("{ x: 'x', value: 'value' }");
//        Mapping series2Data = set.mapAs("{ x: 'x', value: 'value2' }");
//        Mapping series3Data = set.mapAs("{ x: 'x', value: 'value3' }");

        polar.column(series1Data);

//        polar.column(series2Data);
//
//        polar.column(series3Data);

//        polar.setPalette("#ffffff");


//        polar.setTitle("Company Profit Dynamic in Regions by Year");
//        polar.selectMarqueeFill("123678",100);

        polar.setSortPointsByX(true)
                .setDefaultSeriesType(PolarSeriesType.COLUMN)
                .setYAxis(false)

                .setXScale(ScaleTypes.ORDINAL);


//        polar.getTitle().getMargin().setBottom(20d);



//        ((ScalesLinear) polar.getYScale()).setStackMode(ScaleStackMode.VALUE);

        polar.getTooltip()
//                .setValuePrefix("$")
                .setDisplayMode(TooltipDisplayMode.UNION);
//        polar.getPalette().setCount(16);
        polar.setYGrid(false);
        polar.setXGrid(false);
        polar.setInnerRadius(5);

//        polar.setMarkerPalette("jjj");
       polar.setLegend(true);
       polar.setLegend("District");
//        polar.setLabels("jjjj");
        Log.e("getPlette"," "+polar.getPalette());
//        polar.getPalette();

//        polar

//        polar.getHovered().dummyFill("#00FFFF",255);





        anyChartView.setChart(polar);
    }

    private class CustomDataEntry extends ValueDataEntry {
        CustomDataEntry(String x, Number value) {
            super(x, value);
        /* setValue("value", value);
         setValue("value", value);*/
        }
    }
}

**Comment by Shestac92** [comment]
@1007047 
You can customize the series color and set series name (which is shown in legend label) with the following code:
```
PolarSeriesColumn series = polar.column(series1Data);
series.setName("District");
series.setFill("#00FFFF");
series.setStroke("#00FFFF");
```
Footer image is credits. If you want to customize or disable any part of credits placed in your chart, you can purchase a license at [AnyChart Website](https://www.anychart.com/buy/). 
To register your copy and enable credits removal put this in your code in the very beginning:
`anychart.licenseKey("YOUR-LICENSE-KEY");`

**Comment by krishtrp** [comment]
not able to remove the anychart view trial version text on bottom.please help

**Comment by loki20beta** [comment]
@krishtrp do you own a license and have a license key? if so, you need to input it https://github.com/AnyChart/AnyChart-Android/wiki/Credits#license and then disable or change credits.

**Comment by krishtrp** [comment]
@loki20beta -Thanks for your response.I didnt have a license key.Let me check
