### ISSUE TITLE
How to change PieChart Slices Fill colors

### ISSUE THREAD

**Issue by seveli** [AnyChart/AnyChart-Android#84]
Hello, I'm trying to set custom colors for the piechart slices, but it seems that there's no method for that. 
i saw the issue ( https://github.com/AnyChart/AnyChart-Android/issues/37 ) but it's a different type of charts and that method don't apply on the pie chart. could you help me?

Thank you.

**Comment by imaximova** [comment]
Hello, @seveli 
You can set a palette for your pie chart like this for example: chart.palette(["#90caf9", "#80cbc4", "#aed581", "#e6ee9c", "#ffcc80"])
Find the other palette setting options here: https://api.anychart.com/anychart.charts.Pie#palette

**Comment by appsVorstel** [comment]
pie.palette().itemAt(0,**getResources().getColor(R.color.black)**);

**Comment by vivekchaudhary1301** [comment]
For kotlin you use 

var colorlist = arrayof("#3c9743","#fc671a,....)
AnyChart.pie().pallete(colorlist)
