### ISSUE TITLE
How to plot pie chart with changing data on user click?

### ISSUE THREAD

**Issue by Jeetin9410** [AnyChart/AnyChart-Android#85]
I m using the trial version , and trying to plot pie chart.....In my case the data for pie chart changes on user click.
Please tell me how to implement this thing. What is happening now is that the first data that i used to set in pie, is getting permanent.....and whatever the data i set for next time does not work with pie chart. The piechart shows the same data of very first time.Please help ` 

private void generateGraph(int unmarked,int absent,int present,int latePresent){
        // these are absent, present of student
        Log.e( "unG",unmarked+"" );
        Log.e( "abG",absent+"" );
        Log.e( "PrG",present+"" );
        Log.e( "LpG",latePresent+"" );
      final  Pie pie = AnyChart.pie();

        pie.setOnClickListener(new ListenersInterface.OnClickListener(new String[]{"x", "value"}) {
            @Override
            public void onClick(Event event) {
                Toast.makeText(getContext(), event.getData().get("x") + ":" + event.getData().get("value"), Toast.LENGTH_SHORT).show();
            }
        });

        List<DataEntry> data1 = new ArrayList<>();
        data1.add(new ValueDataEntry("Unmarked", unmarked));
        data1.add(new ValueDataEntry("Absent", absent));
        data1.add(new ValueDataEntry("Present", present));
        data1.add(new ValueDataEntry("LatePresent", latePresent));

        pie.data(data1);

        pie.title("Attendance Chart ");
        pie.legend()
                .position("center")
                .itemsLayout( LegendLayout.HORIZONTAL)
                .align( Align.CENTER);
        anyChartView.setChart(pie);
    }`

**Comment by Shestac92** [comment]
@Jeetin9410 
Check [this code sample](https://gist.github.com/ArsenyMalkov/4f13aca9bdde09abd6547b2fde5bede6) which describes how to update the pie chart. You can use the same approach to update your chart on the click event.

**Comment by Jeetin9410** [comment]
The sample code you listed will work for updating the pie chart after some time delay....But I want it to change on user click.....Whatever the data user selects....The pie chart respectively to that data should be displayed.

**Comment by Shestac92** [comment]
@Jeetin9410 
You can execute the chart updating in any event handler.
You can use the chart listeners, for details, please [check this wiki article.](https://github.com/AnyChart/AnyChart-Android/wiki/Event-Listeners)

**Comment by Jeetin9410** [comment]
I tried the Custom data Entry code , you mentioned but i was unable to set data in piechart due this syntax
 pie.setData(data);
Android studio is showing the error as " Cannot resolve method 'setData()' "

**Comment by Shestac92** [comment]
@Jeetin9410 
I'm afraid the wiki article provides deprecated API.
Use `pie.data(data);` instead of `pie.setData()` just like [in this sample.](https://gist.github.com/ArsenyMalkov/4f13aca9bdde09abd6547b2fde5bede6)

**Comment by Jeetin9410** [comment]
From the beginning , i was using the same i.e "pie.data(data)"  and nothing is working accordingly.

**Comment by Shestac92** [comment]
@Jeetin9410 
I have just checked the code using the current version of the library and it works well. 
![pieUpdate](https://user-images.githubusercontent.com/24609062/54505601-80a6ea00-4973-11e9-9137-9eb398f2f6b7.gif)

I used the code provided in the previous comment.

What version of the library are you using? Please, try to update your library up to the latest version. This approach will work.
