### ISSUE TITLE
How to change column colors on condition

### ISSUE THREAD

**Issue by johnybi** [AnyChart/AnyChart-Android#86]
Hello,
I am using anychart to display Key Performance Indicators and my intention is to fill the color of the individual bar after comparing with the target, example, green above the target and red unde the target.
I put a condition to select the values to change colors and then I wrote this line of code: 
series1.select(vecFalse).color("#b00010"); 
The question is that the opposite values get the colour and the selected values get with the grey/black color

**Comment by Shestac92** [comment]
@johnybi 
You can implement condition coloring using a fill function. The snippet below color columns yellow if the column value is lower than 10000 and color blue otherwise.
```
        Cartesian chart = AnyChart.column();

        List<DataEntry> data = new ArrayList<>();
        data.add(new ValueDataEntry("Apples", 9500));
        data.add(new ValueDataEntry("Pears", 12000));
        data.add(new ValueDataEntry("Bananas", 13000));
        data.add(new ValueDataEntry("Grapes", 8000));
        data.add(new ValueDataEntry("Oranges", 6500));

        Column series = chart.column(data);
        series.fill("function() {" +
                "            if (this.value < 10000)" +
                "                return 'yellow';" +
                "            return 'blue';" +
                "        }");

        anyChartView.setChart(chart);
```

**Comment by fabiolacerda** [comment]
in the "this" object return only the ".value", if you want to validate another field for example "this.getData ('product')" the value is not returned
