### ISSUE TITLE
How to disable long-press options on any chart? 

### ISSUE THREAD

**Issue by Prashant-Chandel** [AnyChart/AnyChart-Android#88]
<img width="92" alt="any chart" src="https://user-images.githubusercontent.com/17541340/55479114-f5984600-563a-11e9-9235-82f27be32979.png">
These options appear when we long click on the chart plesase let me know how to disable that .

**Comment by imaximova** [comment]
@Prashant-Chandel this is a context menu, you can disable it by writing this: chart.contextMenu(false);
Learn more at https://docs.anychart.com/Common_Settings/UI_Controls/Context_Menu#enabling_/_disabling

**Comment by Prashant-Chandel** [comment]
@imaximova Thank you!
