### ISSUE TITLE
How do i customise the onclick for the chart?

### ISSUE THREAD

**Issue by aadesh0118** [AnyChart/AnyChart-Android#9]
Currently when i click the chart it gives the default dialog. How do i replace it with my own?

**Comment by Shestac92** [comment]
@aadesh0118 
By the click on the chart, a default tooltip is appearing. In the current version of AnyChart Android library 0.2.0 you can't replace the tooltip with your own element. But you customize it very deeply (appearance, content, behaviour). 
The code below changes the tooltip's appearance of a pie chart.
```javascript
pieChart.getTooltip().setFontColor("orange");
pieChart.getTooltip().getTitle()
        .setFontColor("lightgrey")
        .setFontFamily("Calibri")
        .setFontDecoration(Decoration.UNDERLINE)
        .setFontWeight(400);
pieChart.getTooltip().getBackground()
        .setFill("#663399 0.8")
        .setStroke("green")
        .setCornerType(BackgroundCornersType.ROUND_INNER)
        .setCorners(5, 15, 5, 5);
```
The result:
![pietooltip](https://user-images.githubusercontent.com/24609062/39612501-9e267bd0-4f92-11e8-8037-022bf90bc090.jpg)

**Comment by aadesh0118** [comment]
So if i want to change the "value "and "Percent value" and display only the title. Can i do that?

**Comment by Shestac92** [comment]
@aadesh0118 
in this case you can disable body and separator like this:
```javascript
pieChart.getTooltip().setTitle(false);
pieChart.getTooltip().setFormat("My title");
pieChart.getTooltip().getSeparator().setEnabled(false);
```

**Comment by Shestac92** [comment]
Unfortunately, in the current version of the library, the onclik event setting may not work. We are working on a fix for this.
But you can achieve it with the following line:
```javascript
cloud.getTooltip().setFormat("{%x} : {%value}");
```

**Comment by aadesh0118** [comment]
Ah.. Thats a shame. What i was trying to do was to display just the value when on clicked. But apparently thats not possible eh..?

**Comment by Shestac92** [comment]
@aadesh0118 
Do you mean that you want to show a tooltip only with a value by the click on a pie's slice?

**Comment by Shestac92** [comment]
@aadesh0118 
You can show only value in the tooltip by the click on pie's slice like this:
```javascript
pie.getTooltip().setTitle(false);
pie.getTooltip().setFormat("{%value}");
pie.getTooltip().getSeparator().setEnabled(false);
```
The result:
![pietooltip](https://user-images.githubusercontent.com/24609062/39855575-0b70af50-545f-11e8-9a52-5925349f24a2.jpg)

**Comment by aadesh0118** [comment]
Thanks. Thats all i wanted.
