### ISSUE TITLE
Combile Area and line chart

### ISSUE THREAD

**Issue by shiv2810** [AnyChart/AnyChart-Android#93]
Is there any way to combine area chart with line chart?

**Comment by imaximova** [comment]
@shiv2810, you can just create two series: area and line. Here is a multi-series chart sample: https://github.com/AnyChart/AnyChart-Android/blob/master/sample/src/main/java/com/anychart/sample/charts/LineChartActivity.java
Use it to create your own, and don't forget to set the types properly:
Line series1 = cartesian.line(series1Mapping);
Line series2 = cartesian.area(series2Mapping)
