### ISSUE TITLE
While using area chart . I want to print values from tooltip to textview. like when I click on 2018 year tooltip shows all data of that year. I want to print that data.

### ISSUE THREAD

**Issue by shiv2810** [AnyChart/AnyChart-Android#94]

**Comment by Shestac92** [comment]
@shiv2810 
You can achieve that using eventListeners.
[The repo wiki article](https://github.com/AnyChart/AnyChart-Android/wiki/Event-Listeners) describes the basics of using them.

Here is the code of an Area chart with event listener which returns X and Value data fields of a clicked point.
```
        Cartesian chart = AnyChart.area();

        List<DataEntry> data = new ArrayList<>();
        data.add(new ValueDataEntry("Apples", 9500));
        data.add(new ValueDataEntry("Pears", 12000));
        data.add(new ValueDataEntry("Bananas", 13000));
        data.add(new ValueDataEntry("Grapes", 8000));
        data.add(new ValueDataEntry("Oranges", 6500));

        Area series = chart.area(data);

        chart.setOnClickListener(new ListenersInterface.OnClickListener(new String[]{"x", "value"}) {
            @Override
            public void onClick(Event event) {
                String str = event.getData().get("x");
                String str2 = event.getData().get("value");
                Log.i("user", str);
                Log.i("user", str2);
            }
        });

        anyChartView.setChart(chart);
```

**Comment by shiv2810** [comment]
Thank You for quick reply. When I tried this it is showing me value as
5.9447772E7
while my data is 59447772
and this value can also be a decimal number.

**Comment by Shestac92** [comment]
@shiv2810 
Unfortunately, there's no way to affect the number notation, but you can convert the output value to the required format. For decimals, you can the approach described in [this thread](https://stackoverflow.com/questions/13064567/java-beginner-converting-scientific-notation-to-decimal).

**Comment by shiv2810** [comment]
Thanks
