### ISSUE TITLE
@trungdn0401

### ISSUE THREAD

**Issue by shiv2810** [AnyChart/AnyChart-Android#96]
After clearing graph, graph is not showing. Here is My code.

      anyChartView.clear();
        APIlib.getInstance().setActiveAnyChartView(anyChartView);

        Cartesian areaChart = AnyChart.area();

        areaChart.animation(true);

        Crosshair crosshair = areaChart.crosshair();
        crosshair.enabled(true);
        // TODO yStroke xStroke in crosshair
        crosshair.yStroke((Stroke) null, null, null, (String) null, (String) null)
                .xStroke("#fff", 1d, null, (String) null, (String) null)
                .zIndex(39d);
        crosshair.yLabel(0).enabled(true);

        areaChart.yScale().stackMode(ScaleStackMode.VALUE);

        List<DataEntry> seriesData = new ArrayList<>();
        for (int i = 0; i < reinsuranceGraphPojo.getChart().size(); i++) {
            seriesData.add(new CustomDataEntry(reinsuranceGraphPojo.getChart().get(i).getYear(), reinsuranceGraphPojo.getChart().get(i).getLimitReducedByPrepayM1(), reinsuranceGraphPojo.getChart().get(i).getLimitReducedByPrepayM2(),reinsuranceGraphPojo.getChart().get(i).getLimitReducedByPrepayM3(),reinsuranceGraphPojo.getChart().get(i).getLimitReducedByPrepayM4(), reinsuranceGraphPojo.getChart().get(i).getLimitReducedByPrepayB1(), reinsuranceGraphPojo.getChart().get(i).getLimitReducedByPrepayB2(), reinsuranceGraphPojo.getChart().get(i).getLimitReducedByPrepayB3(), reinsuranceGraphPojo.getChart().get(i).getLimitReducedByPrepayB4(),reinsuranceGraphPojo.getChart().get(i).getCumloss()));

        }

        Set set = Set.instantiate();
        set.data(seriesData);

        Mapping series1Data = set.mapAs("{ x: 'x', value: 'value' }");
        Mapping series2Data = set.mapAs("{ x: 'x', value: 'value2' }");
        Mapping series3Data = set.mapAs("{ x: 'x', value: 'value3' }");
        Mapping series4Data = set.mapAs("{ x: 'x', value: 'value4' }");
        Mapping series5Data = set.mapAs("{ x: 'x', value: 'value5' }");
        Mapping series6Data = set.mapAs("{ x: 'x', value: 'value6' }");
        Mapping series7Data = set.mapAs("{ x: 'x', value: 'value7' }");
        Mapping series8Data = set.mapAs("{ x: 'x', value: 'value8' }");
        Mapping jumpLineData = set.mapAs("{ x: 'x', value: 'jumpLine' }");

        Line jumpLine = areaChart.line(jumpLineData);
        jumpLine.stroke("2 #7700ce");
        jumpLine.labels().enabled(false);

        Area series1 = areaChart.area(series1Data);
        series1.name("M1");
        series1.normal().fill("#11e200", 0.3);
        series1.markers().zIndex(100d);

        areaChart.legend().enabled(false);
        areaChart.legend().fontSize(13d);
        areaChart.legend().padding(0d, 0d, 20d, 0d);

        areaChart.xAxis(0).title(false);
        areaChart.interactivity().hoverMode(HoverMode.BY_X);

        anyChartView.setChart(areaChart);

**Comment by Shestac92** [comment]
@shiv2810 
For clearing graph we recommend using `dispose()` function. In this case, there's no need in the following two lines at all:
```
  anyChartView.clear();
  APIlib.getInstance().setActiveAnyChartView(anyChartView);
```

For example, If the chart object is stored in the variable `chart`, you can execute the following line:
```
chart.dispose();
```
It removes the chart from the view. After that, you can create a new one as usual.

**Comment by shiv2810** [comment]
Thank You. It worked.
