### ISSUE TITLE
Can't replace data in Pie Chart

### ISSUE THREAD

**Issue by laurachelaru** [AnyChart/AnyChart-Android#97]
Hi! I'm using the AnyChart trial version and I am trying to implement a PieChart whose data changes when the user selects an option from a dropdown menu. When an option is selected the app calls the server for the new information, but unfortunately the data in my PieChart remains the same. 

Here is the code I'm using:

`       @Override
	public void onViewCreated(View view, Bundle savedInstanceState) {
        ....
        AnyChartView salesDistributionChart = activity.findViewById(R.id.sales_distribution_chart);
	APIlib.getInstance().setActiveAnyChartView(salesDistributionChart);

	final Pie salesDistributionPie = AnyChart.pie();

	salesDistributionPie.palette(ColorTemplate.DOMAIN_COLORS_TEXT);

	salesDistributionPie.labels().enabled(false);

	salesDistributionPie.legend()
		.position("bottom")
		.itemsLayout(LegendLayout.HORIZONTAL_EXPANDABLE)
		.align(Align.BOTTOM);

	salesDistributionChart.setChart(salesDistributionPie);

        .....

        projectsSpinner.setItems(projectList, 0, new SpinnerListener() {
		@Override
		public void onItemsSelected(List<KeyPairBoolData> list) {
			for (int i = 0; i < list.size(); i++) {
				if (list.get(i).isSelected()) {
					
					setupGraphsByProject(list.get(i).getId(), salesDistributionPie);
					}
			}
		}
	});

       .....

        }

        protected void setupGraphsByProject(long id, final Pie salesDistributionPie) {
		Retrofit retrofit = ApiClient.getInstance(activity).getRetrofit();
		StatisticsService statisticsService = retrofit.create(StatisticsService.class);

		int agencyId = Integer.parseInt(Storage.getAgencyId(activity));
		final Integer projectId;

		if (id > 0) {
			projectId = (int) id;
		} else {
			projectId = null;
		}

		Call<StatisticsFinancialDetails> financialStatsCall = statisticsService.getFinancialStats(
			agencyId,
			projectId
		);
                financialStatsCall.enqueue(new DefaultApiCallback<StatisticsFinancialDetails>(activity, TAG) {
			@Override
			public void onResponseSuccess(final StatisticsFinancialDetails responseBody,
										  Call<StatisticsFinancialDetails> call, okhttp3.Headers headers) {
                         List<DataEntry> data = new ArrayList<>();
			data.add(new ValueDataEntry ( activity.getResources().getString(R.string.unscheduled), responseBody.getPayments().getUnscheduledValue()));
			data.add(new ValueDataEntry ( activity.getResources().getString(R.string.unpaid), responseBody.getPayments().getNotPayedValue()));
			data.add(new ValueDataEntry ( activity.getResources().getString(R.string.paid), responseBody.getPayments().getPayedValue()));
			data.add(new ValueDataEntry ( activity.getResources().getString(R.string.available), responseBody.getPayments().getAvailableValue()));
			data.add(new ValueDataEntry ( activity.getResources().getString(R.string.discount), responseBody.getPayments().getDiscountValue()));

			salesDistributionPie.data(data);
                  }
         }
`

I have tried to implement the code from [here](https://gist.github.com/ArsenyMalkov/4f13aca9bdde09abd6547b2fde5bede6) as is, but nothing changes in the chart.

Any help on this will be very appreciated. Thank you.

**Comment by Shestac92** [comment]
@laurachelaru 
[The Gist with updating the chart Pie chart ](https://gist.github.com/ArsenyMalkov/4f13aca9bdde09abd6547b2fde5bede6) works well, please, make sure that you are using the latest version of the library.
![updatingPieChart](https://user-images.githubusercontent.com/24609062/58450089-f67fbc80-813f-11e9-8949-36553732257e.gif)

As your application gets data from the server and it takes time, please, make sure that the Pie chart is updated after the data has been loaded from the server.

**Comment by laurachelaru** [comment]
I've updated from 1.1.2 to 3.0.0, however now APIlib cannot be found. Did the [method](https://github.com/AnyChart/AnyChart-Android/wiki/Multiple-charts-in-a-single-layout) to add multiple AnyCharts to one layout change?

**Comment by Shestac92** [comment]
@laurachelaru 
Yes, the APIlib is available. You should add the following import:
```
import com.anychart.APIlib;
```

**Comment by laurachelaru** [comment]
OK, so I've managed to get the PieChart updating properly (I initialized the chart and used a different function to do the update), but when I try to do the same thing with an AreaChart I get the following strange behavior:
This is the initial chart:
![screenshot1](https://user-images.githubusercontent.com/2284592/58940404-0facec80-8782-11e9-9786-97011c7e7e03.jpg)

This is the updated chart:
![screenshot2](https://user-images.githubusercontent.com/2284592/58940432-1d627200-8782-11e9-94ba-39ba0cf9b199.jpg)

This is the code I'm using:

`public class TestAreaChart extends BaseFragment implements View.OnClickListener{

	@BindView(R.id.pie_chart)
	protected AnyChartView pieChart;

	@BindView(R.id.area_chart)
	protected AnyChartView areaChart;

	@BindView(R.id.change_button)
	protected Button changeButton;

	protected Pie pie;
	protected Cartesian area;

	@Override
	public View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
		View view = inflater.inflate(R.layout.test_area_chart, container, false);

		ButterKnife.bind(this, view);

		changeButton.setOnClickListener(this);

		return view;
	}

	@Override
	public void onViewCreated(View view, Bundle savedInstanceState) {
		APIlib.getInstance().setActiveAnyChartView(pieChart);
		pie = AnyChart.pie();

		List<DataEntry> data = new ArrayList<>();
		data.add(new ValueDataEntry("Apples", 6371664));
		data.add(new ValueDataEntry("Pears", 789622));
		data.add(new ValueDataEntry("Bananas", 7216301));
		data.add(new ValueDataEntry("Grapes", 1486621));
		data.add(new ValueDataEntry("Oranges", 1200000));

		pie.data(data);

		pieChart.setChart(pie);


		APIlib.getInstance().setActiveAnyChartView(areaChart);
		area = AnyChart.area();

		List<DataEntry> seriesData = new ArrayList<>();
		seriesData.add(new CustomDataEntry("Q2 2014", 17.982, 10.941, 9.835, 4.047, 2.841));
		seriesData.add(new CustomDataEntry("Q3 2014", 17.574, 8.659, 6.230, 2.627, 2.242));
		seriesData.add(new CustomDataEntry("Q4 2014", 19.75, 10.35, 6.292, 3.595, 2.136));
		seriesData.add(new CustomDataEntry("Q1 2015", 30.6, 17.2, 16.1, 5.4, 5.2));
		seriesData.add(new CustomDataEntry("Q2 2015", 21.316, 12.204, 16.823, 3.457, 4.210));
		seriesData.add(new CustomDataEntry("Q3 2015", 20.209, 10.342, 13.23, 2.872, 2.959));
		seriesData.add(new CustomDataEntry("Q4 2015", 21.773, 10.577, 12.518, 3.929, 2.704));
		seriesData.add(new CustomDataEntry("Q1 2016", 29.3, 17.9, 18.4, 4.8, 5.4));

		Set set = Set.instantiate();
		set.data(seriesData);
		Mapping series1Data = set.mapAs("{ x: 'x', value: 'value' }");
		Mapping series2Data = set.mapAs("{ x: 'x', value: 'value2' }");
		Mapping series3Data = set.mapAs("{ x: 'x', value: 'value3' }");
		Mapping series4Data = set.mapAs("{ x: 'x', value: 'value4' }");
		Mapping series5Data = set.mapAs("{ x: 'x', value: 'value5' }");

		Area series1 = area.area(series1Data);
		series1.name("Americas");
		series1.stroke("3 #fff");
		series1.hovered().stroke("3 #fff");
		series1.hovered().markers().enabled(true);
		series1.hovered().markers()
			.type(MarkerType.CIRCLE)
			.size(4d)
			.stroke("1.5 #fff");
		series1.markers().zIndex(100d);

		Area series2 = area.area(series2Data);
		series2.name("Europe");
		series2.stroke("3 #fff");
		series2.hovered().stroke("3 #fff");
		series2.hovered().markers().enabled(true);
		series2.hovered().markers()
			.type(MarkerType.CIRCLE)
			.size(4d)
			.stroke("1.5 #fff");
		series2.markers().zIndex(100d);

		Area series3 = area.area(series3Data);
		series3.name("Greater China");
		series3.stroke("3 #fff");
		series3.hovered().stroke("3 #fff");
		series3.hovered().markers().enabled(true);
		series3.hovered().markers()
			.type(MarkerType.CIRCLE)
			.size(4d)
			.stroke("1.5 #fff");
		series3.markers().zIndex(100d);

		Area series4 = area.area(series4Data);
		series4.name("Japan");
		series4.stroke("3 #fff");
		series4.hovered().stroke("3 #fff");
		series4.hovered().markers().enabled(true);
		series4.hovered().markers()
			.type(MarkerType.CIRCLE)
			.size(4d)
			.stroke("1.5 #fff");
		series4.markers().zIndex(100d);

		Area series5 = area.area(series5Data);
		series5.name("Rest of Asia Pacific");
		series5.stroke("3 #fff");
		series5.hovered().stroke("3 #fff");
		series5.hovered().markers().enabled(true);
		series5.hovered().markers()
			.type(MarkerType.CIRCLE)
			.size(4d)
			.stroke("1.5 #fff");
		series5.markers().zIndex(100d);

		area.legend().enabled(true);
		area.legend().fontSize(13d);
		area.legend().padding(0d, 0d, 20d, 0d);

		area.xAxis(0).title(false);
		area.yAxis(0).title("Revenue (in Billons USD)");

		area.interactivity().hoverMode(HoverMode.BY_X);
		area.tooltip()
			.valuePrefix("$")
			.valuePostfix(" bln.")
			.displayMode(TooltipDisplayMode.UNION);

		areaChart.setChart(area);
	}

	@Override
	public void onClick(View view) {
		switch (view.getId()) {
			case R.id.change_button:
				APIlib.getInstance().setActiveAnyChartView(pieChart);
				List<DataEntry> data = new ArrayList<>();
				data.add(new ValueDataEntry("Apples", new Random().nextDouble() * 140d));
				data.add(new ValueDataEntry("Pears", new Random().nextDouble() * 140d));
				pie.data(data);

				APIlib.getInstance().setActiveAnyChartView(areaChart);
				List<DataEntry> seriesData = new ArrayList<>();
				seriesData.add(new CustomDataEntry("Q2 2014", new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble()));
				seriesData.add(new CustomDataEntry("Q3 2014", new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble()));
				seriesData.add(new CustomDataEntry("Q4 2014", new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble()));
				seriesData.add(new CustomDataEntry("Q1 2015", new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble()));
				seriesData.add(new CustomDataEntry("Q2 2015", new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble()));
				seriesData.add(new CustomDataEntry("Q3 2015", new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(),new Random().nextDouble(), new Random().nextDouble()));
				seriesData.add(new CustomDataEntry("Q4 2015", new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble()));
				seriesData.add(new CustomDataEntry("Q1 2016", new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble()));

				area.data(seriesData );
				break;
		}
	}

	private class CustomDataEntry extends ValueDataEntry {
		CustomDataEntry(String x, Number value, Number value2, Number value3, Number value4, Number value5) {
			super(x, value);
			setValue("value2", value2);
			setValue("value3", value3);
			setValue("value4", value4);
			setValue("value5", value5);
		}
	}
}`

Any insight will be very appreciated.

**Comment by Shestac92** [comment]
@laurachelaru 
For the area chart you created separated mappings for every series, but then you are applying new data to the chart. You should follow the same approach, series should observe data changes. To achieve that, try to update the dataSet:
```
			APIlib.getInstance().setActiveAnyChartView(areaChart);
			List<DataEntry> seriesData = new ArrayList<>();
			seriesData.add(new CustomDataEntry("Q2 2014", new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble()));
			seriesData.add(new CustomDataEntry("Q3 2014", new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble()));
			seriesData.add(new CustomDataEntry("Q4 2014", new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble()));
			seriesData.add(new CustomDataEntry("Q1 2015", new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble()));
			seriesData.add(new CustomDataEntry("Q2 2015", new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble()));
			seriesData.add(new CustomDataEntry("Q3 2015", new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(),new Random().nextDouble(), new Random().nextDouble()));
			seriesData.add(new CustomDataEntry("Q4 2015", new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble()));
			seriesData.add(new CustomDataEntry("Q1 2016", new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble(), new Random().nextDouble()));

set.data(seriesData); // update the existing set with already created mappings
			break;
```

**Comment by laurachelaru** [comment]
Hi! Yes that worked! Thank you very much! 

Another question: is there a way to clear the chart of data? When I update my chart there is the possibility that there may be fewer series than the initial chart and this behavior happens: 

The initial chart, with 5 series:
![Screenshot3](https://user-images.githubusercontent.com/2284592/59014091-60851980-8844-11e9-9403-85f286031860.jpg)

The updated chart with 4 series:
![Screenshot4](https://user-images.githubusercontent.com/2284592/59014102-6aa71800-8844-11e9-9699-d2b2ea2bcaee.jpg)


Here is my code:

`public class TestAreaChart extends BaseFragment implements View.OnClickListener{

	@BindView(R.id.pie_chart)
	protected AnyChartView pieChart;

	@BindView(R.id.area_chart)
	protected AnyChartView areaChart;

	@BindView(R.id.change_button)
	protected Button changeButton;

	protected Pie pie;
	protected Cartesian area;
	protected Set areaSet;

	@Override
	public View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
		View view = inflater.inflate(R.layout.test_area_chart, container, false);

		ButterKnife.bind(this, view);

		changeButton.setOnClickListener(this);

		return view;
	}

	@Override
	public void onViewCreated(View view, Bundle savedInstanceState) {
		APIlib.getInstance().setActiveAnyChartView(pieChart);
		pie = AnyChart.pie();

		List<DataEntry> data = new ArrayList<>();
		data.add(new ValueDataEntry("Apples", 6371664));
		data.add(new ValueDataEntry("Pears", 789622));
		data.add(new ValueDataEntry("Bananas", 7216301));
		data.add(new ValueDataEntry("Grapes", 1486621));
		data.add(new ValueDataEntry("Oranges", 1200000));

		pie.data(data);

		pieChart.setChart(pie);


		APIlib.getInstance().setActiveAnyChartView(areaChart);
		area = AnyChart.area();

		List<DataEntry> seriesData = new ArrayList<>();
		List<Number> values1 = new ArrayList();
		values1.add(new Random().nextDouble());
		values1.add(new Random().nextDouble());
		values1.add(new Random().nextDouble());
		values1.add(new Random().nextDouble());
		values1.add(new Random().nextDouble());

		List<Number> values2 = new ArrayList();
		values2.add(new Random().nextDouble());
		values2.add(new Random().nextDouble());
		values2.add(new Random().nextDouble());
		values2.add(new Random().nextDouble());
		values2.add(new Random().nextDouble());

		List<Number> values3 = new ArrayList();
		values3.add(new Random().nextDouble());
		values3.add(new Random().nextDouble());
		values3.add(new Random().nextDouble());
		values3.add(new Random().nextDouble());
		values3.add(new Random().nextDouble());

		List<Number> values4 = new ArrayList();
		values4.add(new Random().nextDouble());
		values4.add(new Random().nextDouble());
		values4.add(new Random().nextDouble());
		values4.add(new Random().nextDouble());
		values4.add(new Random().nextDouble());

		List<Number> values5 = new ArrayList();
		values5.add(new Random().nextDouble());
		values5.add(new Random().nextDouble());
		values5.add(new Random().nextDouble());
		values5.add(new Random().nextDouble());
		values5.add(new Random().nextDouble());

		List<Number> values6 = new ArrayList();
		values6.add(new Random().nextDouble());
		values6.add(new Random().nextDouble());
		values6.add(new Random().nextDouble());
		values6.add(new Random().nextDouble());
		values6.add(new Random().nextDouble());

		List<Number> values7 = new ArrayList();
		values7.add(new Random().nextDouble());
		values7.add(new Random().nextDouble());
		values7.add(new Random().nextDouble());
		values7.add(new Random().nextDouble());
		values7.add(new Random().nextDouble());

		List<Number> values8 = new ArrayList();
		values8.add(new Random().nextDouble());
		values8.add(new Random().nextDouble());
		values8.add(new Random().nextDouble());
		values8.add(new Random().nextDouble());
		values8.add(new Random().nextDouble());

		seriesData.add(new AreaChartDataEntry("Q2 2014", values1));
		seriesData.add(new AreaChartDataEntry("Q3 2014", values2));
		seriesData.add(new AreaChartDataEntry("Q4 2014", values3));
		seriesData.add(new AreaChartDataEntry("Q1 2015", values4));
		seriesData.add(new AreaChartDataEntry("Q2 2015", values5));
		seriesData.add(new AreaChartDataEntry("Q3 2015", values6));
		seriesData.add(new AreaChartDataEntry("Q4 2015", values7));
		seriesData.add(new AreaChartDataEntry("Q1 2016", values8));

		areaSet = Set.instantiate();
		areaSet.data(seriesData);
		Mapping series1Data = areaSet.mapAs("{ x: 'x', value: 'value' }");
		Mapping series2Data = areaSet.mapAs("{ x: 'x', value: 'value2' }");
		Mapping series3Data = areaSet.mapAs("{ x: 'x', value: 'value3' }");
		Mapping series4Data = areaSet.mapAs("{ x: 'x', value: 'value4' }");
		Mapping series5Data = areaSet.mapAs("{ x: 'x', value: 'value5' }");

		Area series1 = area.area(series1Data);
		series1.name("Americas");
		series1.stroke("3 #fff");
		series1.hovered().stroke("3 #fff");
		series1.hovered().markers().enabled(true);
		series1.hovered().markers()
			.type(MarkerType.CIRCLE)
			.size(4d)
			.stroke("1.5 #fff");
		series1.markers().zIndex(100d);

		Area series2 = area.area(series2Data);
		series2.name("Europe");
		series2.stroke("3 #fff");
		series2.hovered().stroke("3 #fff");
		series2.hovered().markers().enabled(true);
		series2.hovered().markers()
			.type(MarkerType.CIRCLE)
			.size(4d)
			.stroke("1.5 #fff");
		series2.markers().zIndex(100d);

		Area series3 = area.area(series3Data);
		series3.name("Greater China");
		series3.stroke("3 #fff");
		series3.hovered().stroke("3 #fff");
		series3.hovered().markers().enabled(true);
		series3.hovered().markers()
			.type(MarkerType.CIRCLE)
			.size(4d)
			.stroke("1.5 #fff");
		series3.markers().zIndex(100d);

		Area series4 = area.area(series4Data);
		series4.name("Japan");
		series4.stroke("3 #fff");
		series4.hovered().stroke("3 #fff");
		series4.hovered().markers().enabled(true);
		series4.hovered().markers()
			.type(MarkerType.CIRCLE)
			.size(4d)
			.stroke("1.5 #fff");
		series4.markers().zIndex(100d);

		Area series5 = area.area(series5Data);
		series5.name("Rest of Asia Pacific");
		series5.stroke("3 #fff");
		series5.hovered().stroke("3 #fff");
		series5.hovered().markers().enabled(true);
		series5.hovered().markers()
			.type(MarkerType.CIRCLE)
			.size(4d)
			.stroke("1.5 #fff");
		series5.markers().zIndex(100d);

		area.legend().enabled(true);
		area.legend().fontSize(13d);
		area.legend().padding(0d, 0d, 20d, 0d);

		area.xAxis(0).title(false);
		area.yAxis(0).title("Revenue (in Billons USD)");

		area.interactivity().hoverMode(HoverMode.BY_X);
		area.tooltip()
			.valuePrefix("$")
			.valuePostfix(" bln.")
			.displayMode(TooltipDisplayMode.UNION);

		areaChart.setChart(area);
	}

	@Override
	public void onClick(View view) {
		switch (view.getId()) {
			case R.id.change_button:
				APIlib.getInstance().setActiveAnyChartView(pieChart);
				List<DataEntry> data = new ArrayList<>();
				data.add(new ValueDataEntry("Apples", new Random().nextDouble() * 140d));
				data.add(new ValueDataEntry("Pears", new Random().nextDouble() * 140d));
				pie.data(data);

				area.dispose();
				areaChart.clear();
				APIlib.getInstance().setActiveAnyChartView(areaChart);
				List<DataEntry> seriesData = new ArrayList<>();

				area = AnyChart.area();

				List<Number> values1 = new ArrayList();
				values1.add(new Random().nextDouble());
				values1.add(new Random().nextDouble());
				values1.add(new Random().nextDouble());
				values1.add(new Random().nextDouble());

				List<Number> values2 = new ArrayList();
				values2.add(new Random().nextDouble());
				values2.add(new Random().nextDouble());
				values2.add(new Random().nextDouble());
				values2.add(new Random().nextDouble());

				List<Number> values3 = new ArrayList();
				values3.add(new Random().nextDouble());
				values3.add(new Random().nextDouble());
				values3.add(new Random().nextDouble());
				values3.add(new Random().nextDouble());

				List<Number> values4 = new ArrayList();
				values4.add(new Random().nextDouble());
				values4.add(new Random().nextDouble());
				values4.add(new Random().nextDouble());
				values4.add(new Random().nextDouble());

				List<Number> values5 = new ArrayList();
				values5.add(new Random().nextDouble());
				values5.add(new Random().nextDouble());
				values5.add(new Random().nextDouble());
				values5.add(new Random().nextDouble());

				List<Number> values6 = new ArrayList();
				values6.add(new Random().nextDouble());
				values6.add(new Random().nextDouble());
				values6.add(new Random().nextDouble());
				values6.add(new Random().nextDouble());

				List<Number> values7 = new ArrayList();
				values7.add(new Random().nextDouble());
				values7.add(new Random().nextDouble());
				values7.add(new Random().nextDouble());
				values7.add(new Random().nextDouble());

				List<Number> values8 = new ArrayList();
				values8.add(new Random().nextDouble());
				values8.add(new Random().nextDouble());
				values8.add(new Random().nextDouble());
				values8.add(new Random().nextDouble());

				seriesData.add(new AreaChartDataEntry("Q2 2014", values1));
				seriesData.add(new AreaChartDataEntry("Q3 2014", values2));
				seriesData.add(new AreaChartDataEntry("Q4 2014", values3));
				seriesData.add(new AreaChartDataEntry("Q1 2015", values4));
				seriesData.add(new AreaChartDataEntry("Q2 2015", values5));
				seriesData.add(new AreaChartDataEntry("Q3 2015", values6));
				seriesData.add(new AreaChartDataEntry("Q4 2015", values7));
				seriesData.add(new AreaChartDataEntry("Q1 2016", values8));

				areaSet.data(seriesData);
				Mapping series1Data = areaSet.mapAs("{ x: 'x', value: 'value' }");
				Mapping series2Data = areaSet.mapAs("{ x: 'x', value: 'value2' }");
				Mapping series3Data = areaSet.mapAs("{ x: 'x', value: 'value3' }");
				Mapping series4Data = areaSet.mapAs("{ x: 'x', value: 'value4' }");

				Area series1 = area.area(series1Data);
				series1.name("Americas");
				series1.stroke("3 #fff");
				series1.hovered().stroke("3 #fff");
				series1.hovered().markers().enabled(true);
				series1.hovered().markers()
					.type(MarkerType.CIRCLE)
					.size(4d)
					.stroke("1.5 #fff");
				series1.markers().zIndex(100d);

				Area series2 = area.area(series2Data);
				series2.name("Europe");
				series2.stroke("3 #fff");
				series2.hovered().stroke("3 #fff");
				series2.hovered().markers().enabled(true);
				series2.hovered().markers()
					.type(MarkerType.CIRCLE)
					.size(4d)
					.stroke("1.5 #fff");
				series2.markers().zIndex(100d);

				Area series3 = area.area(series3Data);
				series3.name("Greater China");
				series3.stroke("3 #fff");
				series3.hovered().stroke("3 #fff");
				series3.hovered().markers().enabled(true);
				series3.hovered().markers()
					.type(MarkerType.CIRCLE)
					.size(4d)
					.stroke("1.5 #fff");
				series3.markers().zIndex(100d);

				Area series4 = area.area(series4Data);
				series4.name("Japan");
				series4.stroke("3 #fff");
				series4.hovered().stroke("3 #fff");
				series4.hovered().markers().enabled(true);
				series4.hovered().markers()
					.type(MarkerType.CIRCLE)
					.size(4d)
					.stroke("1.5 #fff");
				series4.markers().zIndex(100d);

				areaChart.setChart(area);

				break;
		}
	}

	private class AreaChartDataEntry extends ValueDataEntry {
		AreaChartDataEntry(String x, List<Number> values) {
			super(x, values.get(0));
			for (int i=1; i<values.size(); i++) {
				setValue("value"+String.valueOf(i), values.get(i));
			}
		}
	}
`

Any help will very appreciated.

**Comment by Shestac92** [comment]
@laurachelaru 
Yes, in this case, you can just remove all series from the chart and create the required number of new series.
You can achieve that with the only one line code:
```
// chart variable stores the chart instance
chart.removeAllSeries();
```
That's it! After that, you can create new series as usual.

**Comment by laurachelaru** [comment]
Unfortunately, that doesn't seem to work for me. I still have the old 5 series after doing chart.removeAllSeries(); and creating only 4 series. 

I also tried to simply remove all series on the area on button pressed, which I imagined would leave me with an empty chart, but instead I have the old chart, with no change. 

This is my code: 

`public class TestAreaChart extends BaseFragment implements View.OnClickListener{

	@BindView(R.id.pie_chart)
	protected AnyChartView pieChart;

	@BindView(R.id.area_chart)
	protected AnyChartView areaChart;

	@BindView(R.id.change_button)
	protected Button changeButton;

	protected Pie pie;
	protected Cartesian area;
	protected Set areaSet;

	@Override
	public View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
		View view = inflater.inflate(R.layout.test_area_chart, container, false);

		ButterKnife.bind(this, view);

		changeButton.setOnClickListener(this);

		return view;
	}

	@Override
	public void onViewCreated(View view, Bundle savedInstanceState) {
		APIlib.getInstance().setActiveAnyChartView(pieChart);
		pie = AnyChart.pie();

		List<DataEntry> data = new ArrayList<>();
		data.add(new ValueDataEntry("Apples", 6371664));
		data.add(new ValueDataEntry("Pears", 789622));
		data.add(new ValueDataEntry("Bananas", 7216301));
		data.add(new ValueDataEntry("Grapes", 1486621));
		data.add(new ValueDataEntry("Oranges", 1200000));

		pie.data(data);

		pieChart.setChart(pie);


		APIlib.getInstance().setActiveAnyChartView(areaChart);
		area = AnyChart.area();

		List<DataEntry> seriesData = new ArrayList<>();
		List<Number> values1 = new ArrayList();
		values1.add(new Random().nextDouble());
		values1.add(new Random().nextDouble());
		values1.add(new Random().nextDouble());
		values1.add(new Random().nextDouble());
		values1.add(new Random().nextDouble());

		List<Number> values2 = new ArrayList();
		values2.add(new Random().nextDouble());
		values2.add(new Random().nextDouble());
		values2.add(new Random().nextDouble());
		values2.add(new Random().nextDouble());
		values2.add(new Random().nextDouble());

		List<Number> values3 = new ArrayList();
		values3.add(new Random().nextDouble());
		values3.add(new Random().nextDouble());
		values3.add(new Random().nextDouble());
		values3.add(new Random().nextDouble());
		values3.add(new Random().nextDouble());

		List<Number> values4 = new ArrayList();
		values4.add(new Random().nextDouble());
		values4.add(new Random().nextDouble());
		values4.add(new Random().nextDouble());
		values4.add(new Random().nextDouble());
		values4.add(new Random().nextDouble());

		List<Number> values5 = new ArrayList();
		values5.add(new Random().nextDouble());
		values5.add(new Random().nextDouble());
		values5.add(new Random().nextDouble());
		values5.add(new Random().nextDouble());
		values5.add(new Random().nextDouble());

		List<Number> values6 = new ArrayList();
		values6.add(new Random().nextDouble());
		values6.add(new Random().nextDouble());
		values6.add(new Random().nextDouble());
		values6.add(new Random().nextDouble());
		values6.add(new Random().nextDouble());

		List<Number> values7 = new ArrayList();
		values7.add(new Random().nextDouble());
		values7.add(new Random().nextDouble());
		values7.add(new Random().nextDouble());
		values7.add(new Random().nextDouble());
		values7.add(new Random().nextDouble());

		List<Number> values8 = new ArrayList();
		values8.add(new Random().nextDouble());
		values8.add(new Random().nextDouble());
		values8.add(new Random().nextDouble());
		values8.add(new Random().nextDouble());
		values8.add(new Random().nextDouble());

		seriesData.add(new AreaChartDataEntry("Q2 2014", values1));
		seriesData.add(new AreaChartDataEntry("Q3 2014", values2));
		seriesData.add(new AreaChartDataEntry("Q4 2014", values3));
		seriesData.add(new AreaChartDataEntry("Q1 2015", values4));
		seriesData.add(new AreaChartDataEntry("Q2 2015", values5));
		seriesData.add(new AreaChartDataEntry("Q3 2015", values6));
		seriesData.add(new AreaChartDataEntry("Q4 2015", values7));
		seriesData.add(new AreaChartDataEntry("Q1 2016", values8));

		areaSet = Set.instantiate();
		areaSet.data(seriesData);
		Mapping series1Data = areaSet.mapAs("{ x: 'x', value: 'value' }");
		Mapping series2Data = areaSet.mapAs("{ x: 'x', value: 'value2' }");
		Mapping series3Data = areaSet.mapAs("{ x: 'x', value: 'value3' }");
		Mapping series4Data = areaSet.mapAs("{ x: 'x', value: 'value4' }");
		Mapping series5Data = areaSet.mapAs("{ x: 'x', value: 'value5' }");

		Area series1 = area.area(series1Data);
		series1.name("Americas");
		series1.stroke("3 #fff");
		series1.hovered().stroke("3 #fff");
		series1.hovered().markers().enabled(true);
		series1.hovered().markers()
			.type(MarkerType.CIRCLE)
			.size(4d)
			.stroke("1.5 #fff");
		series1.markers().zIndex(100d);

		Area series2 = area.area(series2Data);
		series2.name("Europe");
		series2.stroke("3 #fff");
		series2.hovered().stroke("3 #fff");
		series2.hovered().markers().enabled(true);
		series2.hovered().markers()
			.type(MarkerType.CIRCLE)
			.size(4d)
			.stroke("1.5 #fff");
		series2.markers().zIndex(100d);

		Area series3 = area.area(series3Data);
		series3.name("Greater China");
		series3.stroke("3 #fff");
		series3.hovered().stroke("3 #fff");
		series3.hovered().markers().enabled(true);
		series3.hovered().markers()
			.type(MarkerType.CIRCLE)
			.size(4d)
			.stroke("1.5 #fff");
		series3.markers().zIndex(100d);

		Area series4 = area.area(series4Data);
		series4.name("Japan");
		series4.stroke("3 #fff");
		series4.hovered().stroke("3 #fff");
		series4.hovered().markers().enabled(true);
		series4.hovered().markers()
			.type(MarkerType.CIRCLE)
			.size(4d)
			.stroke("1.5 #fff");
		series4.markers().zIndex(100d);

		Area series5 = area.area(series5Data);
		series5.name("Rest of Asia Pacific");
		series5.stroke("3 #fff");
		series5.hovered().stroke("3 #fff");
		series5.hovered().markers().enabled(true);
		series5.hovered().markers()
			.type(MarkerType.CIRCLE)
			.size(4d)
			.stroke("1.5 #fff");
		series5.markers().zIndex(100d);

		area.legend().enabled(true);
		area.legend().fontSize(13d);
		area.legend().padding(0d, 0d, 20d, 0d);

		area.xAxis(0).title(false);
		area.yAxis(0).title("Revenue (in Billons USD)");

		area.interactivity().hoverMode(HoverMode.BY_X);
		area.tooltip()
			.valuePrefix("$")
			.valuePostfix(" bln.")
			.displayMode(TooltipDisplayMode.UNION);

		areaChart.setChart(area);
	}

	@Override
	public void onClick(View view) {
		switch (view.getId()) {
			case R.id.change_button:
				APIlib.getInstance().setActiveAnyChartView(pieChart);
				List<DataEntry> data = new ArrayList<>();
				data.add(new ValueDataEntry("Apples", new Random().nextDouble() * 140d));
				data.add(new ValueDataEntry("Pears", new Random().nextDouble() * 140d));
				pie.data(data);

				area.removeAllSeries();
				areaChart.clear();

				areaChart.setChart(area);

				break;
		}
	}

	private class AreaChartDataEntry extends ValueDataEntry {
		AreaChartDataEntry(String x, List<Number> values) {
			super(x, values.get(0));
			for (int i=1; i<values.size(); i++) {
				setValue("value"+String.valueOf(i), values.get(i));
			}
		}
	}
}`

Am I missing something?

**Comment by Shestac92** [comment]
@laurachelaru 
I think you should set the Area chart as active before calling `removeAllSeries()`. Just as you did for pieChart.

```
@Override
public void onClick(View view) {
	switch (view.getId()) {
		case R.id.change_button:
			APIlib.getInstance().setActiveAnyChartView(pieChart);
			List<DataEntry> data = new ArrayList<>();
			data.add(new ValueDataEntry("Apples", new Random().nextDouble() * 140d));
			data.add(new ValueDataEntry("Pears", new Random().nextDouble() * 140d));
			pie.data(data);

APIlib.getInstance().setActiveAnyChartView(area); // <<--- Add this line

			area.removeAllSeries();
			areaChart.clear();

			areaChart.setChart(area);

			break;
	}
}
```

**Comment by laurachelaru** [comment]
Yes! Thank you! I've managed to get it to work properly! 

As a side note, area.removeAllSeries(), by itself, doesn't do the trick. I've had to use the following code to get the chart updating the way I wanted it:

`APIlib.getInstance().setActiveAnyChartView(areaChart);

area.removeAllSeries();
area.dispose();
areaChart.clear();`

Thank you again for all the help.
